import type { IconPack, IconEntry } from "../types";

function emoji(value: string, colorMode?: "static" | "entity_rgb"): IconEntry {
  return {
    icon: { type: "emoji", value },
    defaultStyle: { opacity: 1, colorMode: colorMode ?? "static" },
    stateStyles: {
      on: { opacity: 1, colorMode: colorMode ?? "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const emojiPack: IconPack = {
  id: "emoji",
  name: "Emoji",
  description: "Default emoji icons — zero extra bundle size",
  fallback: emoji("⬡"),
  domains: {
    light: {
      default: {
        icon: { type: "emoji", value: "💡" },
        defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
        stateStyles: {
          on: { opacity: 1, colorMode: "entity_rgb" },
          off: { opacity: 0.5, colorMode: "static" },
          unavailable: { opacity: 0.3, colorMode: "static" },
        },
      },
    },
    switch: { default: emoji("⚡") },
    cover: {
      default: emoji("🪟"),
      states: {
        open: emoji("🪟"),
        opening: emoji("🪟"),
        closed: emoji("🪟"),
        closing: emoji("🪟"),
      },
    },
    sensor: {
      default: emoji("📊"),
      deviceClasses: {
        temperature: { default: emoji("🌡") },
        humidity: { default: emoji("💧") },
        pressure: { default: emoji("🌀") },
        power: { default: emoji("⚡") },
        energy: { default: emoji("🔋") },
        battery: { default: emoji("🔋") },
        illuminance: { default: emoji("☀️") },
        carbon_dioxide: { default: emoji("🫧") },
        carbon_monoxide: { default: emoji("⚠️") },
        gas: { default: emoji("🫧") },
        moisture: { default: emoji("💧") },
        plug: { default: emoji("🔌") },
      },
    },
    binary_sensor: {
      default: emoji("◉"),
      deviceClasses: {
        motion: { default: emoji("🚶") },
        door: { default: emoji("🚪") },
        window: { default: emoji("🪟") },
        vibration: { default: emoji("📳") },
        smoke: { default: emoji("🔥") },
        occupancy: { default: emoji("👤") },
        opening: { default: emoji("🚪") },
        presence: { default: emoji("📡") },
        problem: { default: emoji("⚠️") },
        safety: { default: emoji("🛡") },
        sound: { default: emoji("🔊") },
      },
    },
    climate: {
      default: emoji("🌡"),
      states: {
        heat: emoji("🔥"),
        cool: emoji("❄️"),
        heat_cool: emoji("🔄"),
        auto: emoji("🔄"),
        dry: emoji("💧"),
        fan_only: emoji("🌀"),
        off: emoji("⏻"),
      },
    },
    fan: { default: emoji("🌀") },
    camera: { default: emoji("📷") },
    media_player: {
      default: emoji("🔊"),
      states: {
        playing: emoji("▶️"),
        paused: emoji("⏸️"),
      },
    },
    lock: {
      default: emoji("🔒"),
      states: {
        locked: emoji("🔒"),
        unlocked: emoji("🔓"),
      },
    },
    scene: { default: emoji("🎬") },
    script: { default: emoji("📜") },
    automation: { default: emoji("⚙️") },
    button: { default: emoji("🔘") },
    furniture: {
      default: emoji("🪑"),
      deviceClasses: {
        sofa: { default: emoji("🛋️") },
        bed: { default: emoji("🛏️") },
        table: { default: emoji("🪑") },
        chair: { default: emoji("💺") },
        desk: { default: emoji("🖥️") },
        plant: { default: emoji("🪴") },
        door: { default: emoji("🚪") },
        window: { default: emoji("🪟") },
        toilet: { default: emoji("🚽") },
        shower: { default: emoji("🚿") },
        sink: { default: emoji("🚰") },
        bathtub: { default: emoji("🛁") },
        fridge: { default: emoji("🧊") },
        oven: { default: emoji("♨️") },
        dishwasher: { default: emoji("🍽️") },
        tv: { default: emoji("📺") },
        wardrobe: { default: emoji("🗄️") },
        bookshelf: { default: emoji("📚") },
      },
    },

    /* ──────── Extra categories ──────── */
    lighting: {
      default: emoji("💡"),
      deviceClasses: {
        ceiling_light: { default: emoji("💡") },
        floor_lamp: { default: emoji("🪔") },
        desk_lamp: { default: emoji("🔦") },
        wall_sconce: { default: emoji("💡") },
        chandelier: { default: emoji("✨") },
        led_strip: { default: emoji("🌈") },
        flood_light: { default: emoji("🔆") },
        spotlight: { default: emoji("🔦") },
        string_lights: { default: emoji("🎄") },
        track_light: { default: emoji("💡") },
        coach_lamp: { default: emoji("🏮") },
        lamp: { default: emoji("🪔") },
        outdoor_lamp: { default: emoji("🏮") },
        vanity_light: { default: emoji("💡") },
      },
    },
    appliance: {
      default: emoji("🍳"),
      deviceClasses: {
        microwave: { default: emoji("📻") },
        washing_machine: { default: emoji("🧺") },
        tumble_dryer: { default: emoji("🌀") },
        robot_vacuum: { default: emoji("🤖") },
        coffee_maker: { default: emoji("☕") },
        blender: { default: emoji("🥤") },
        toaster: { default: emoji("🍞") },
        toaster_oven: { default: emoji("🍞") },
        fireplace: { default: emoji("🔥") },
        radiator: { default: emoji("♨️") },
        air_conditioner: { default: emoji("❄️") },
        ceiling_fan: { default: emoji("🌀") },
        curtains: { default: emoji("🪟") },
        iron: { default: emoji("👔") },
        hair_dryer: { default: emoji("💇") },
      },
    },
    electronics: {
      default: emoji("💻"),
      deviceClasses: {
        laptop: { default: emoji("💻") },
        cellphone: { default: emoji("📱") },
        tablet: { default: emoji("📱") },
        router: { default: emoji("📡") },
        printer: { default: emoji("🖨️") },
        keyboard: { default: emoji("⌨️") },
        mouse: { default: emoji("🖱️") },
        monitor: { default: emoji("🖥️") },
        gamepad: { default: emoji("🎮") },
        headphones: { default: emoji("🎧") },
        projector: { default: emoji("📽️") },
        wireless_camera: { default: emoji("📹") },
        wireless_speaker: { default: emoji("🔊") },
        nas: { default: emoji("💾") },
        server: { default: emoji("🖥️") },
        hard_disk: { default: emoji("💿") },
        usb_drive: { default: emoji("💾") },
        smart_card: { default: emoji("💳") },
      },
    },
    outdoor: {
      default: emoji("🌳"),
      deviceClasses: {
        tree: { default: emoji("🌳") },
        pine_tree: { default: emoji("🌲") },
        fence: { default: emoji("🏗️") },
        garage: { default: emoji("🏠") },
        pool: { default: emoji("🏊") },
        grill: { default: emoji("🍖") },
        umbrella: { default: emoji("⛱️") },
        cactus: { default: emoji("🌵") },
        sprout: { default: emoji("🌱") },
        grass: { default: emoji("🌿") },
        leaf: { default: emoji("🍃") },
        tulip: { default: emoji("🌷") },
        barley: { default: emoji("🌾") },
        mushroom: { default: emoji("🍄") },
        compost: { default: emoji("♻️") },
      },
    },
    transport: {
      default: emoji("🚗"),
      deviceClasses: {
        car: { default: emoji("🚗") },
        bicycle: { default: emoji("🚲") },
        motorbike: { default: emoji("🏍️") },
        bus: { default: emoji("🚌") },
        train: { default: emoji("🚆") },
        airplane: { default: emoji("✈️") },
        boat: { default: emoji("⛵") },
        helicopter: { default: emoji("🚁") },
        scooter: { default: emoji("🛴") },
        electric_scooter: { default: emoji("🛴") },
        electric_car: { default: emoji("🔋") },
        ev_station: { default: emoji("⚡") },
        gas_station: { default: emoji("⛽") },
        parking: { default: emoji("🅿️") },
      },
    },
    tools: {
      default: emoji("🔧"),
      deviceClasses: {
        wrench: { default: emoji("🔧") },
        hammer: { default: emoji("🔨") },
        screwdriver: { default: emoji("🪛") },
        saw: { default: emoji("🪚") },
        toolbox: { default: emoji("🧰") },
        tape_measure: { default: emoji("📏") },
        ruler: { default: emoji("📐") },
        pencil_ruler: { default: emoji("✏️") },
      },
    },
    shapes: {
      default: emoji("⭕"),
      deviceClasses: {
        circle: { default: emoji("🔴") },
        circle_outline: { default: emoji("⭕") },
        square: { default: emoji("🟥") },
        square_outline: { default: emoji("⬜") },
        triangle: { default: emoji("🔺") },
        triangle_outline: { default: emoji("△") },
        star: { default: emoji("⭐") },
        star_outline: { default: emoji("☆") },
        heart: { default: emoji("❤️") },
        heart_outline: { default: emoji("♡") },
        diamond: { default: emoji("♦️") },
        diamond_outline: { default: emoji("◇") },
        hexagon: { default: emoji("⬡") },
        octagon: { default: emoji("🛑") },
        octagon_outline: { default: emoji("⬡") },
        pentagon: { default: emoji("⬠") },
        pentagon_outline: { default: emoji("⬠") },
        decagram: { default: emoji("✳️") },
        decagram_outline: { default: emoji("✴️") },
        cross: { default: emoji("✝️") },
        close: { default: emoji("✖️") },
        plus: { default: emoji("➕") },
        minus: { default: emoji("➖") },
        check: { default: emoji("✅") },
      },
    },
    arrows: {
      default: emoji("⬆️"),
      deviceClasses: {
        up: { default: emoji("⬆️") },
        down: { default: emoji("⬇️") },
        left: { default: emoji("⬅️") },
        right: { default: emoji("➡️") },
        up_bold: { default: emoji("🔼") },
        down_bold: { default: emoji("🔽") },
        left_bold: { default: emoji("◀️") },
        right_bold: { default: emoji("▶️") },
        chevron_up: { default: emoji("˄") },
        chevron_down: { default: emoji("˅") },
        chevron_left: { default: emoji("‹") },
        chevron_right: { default: emoji("›") },
      },
    },
    animals: {
      default: emoji("🐾"),
      deviceClasses: {
        dog: { default: emoji("🐕") },
        cat: { default: emoji("🐈") },
        fish: { default: emoji("🐟") },
        bird: { default: emoji("🐦") },
        paw: { default: emoji("🐾") },
        bee: { default: emoji("🐝") },
        turtle: { default: emoji("🐢") },
        rabbit: { default: emoji("🐇") },
        duck: { default: emoji("🦆") },
        owl: { default: emoji("🦉") },
        butterfly: { default: emoji("🦋") },
        horseshoe: { default: emoji("🐴") },
        snake: { default: emoji("🐍") },
        spider: { default: emoji("🕷️") },
      },
    },
    food: {
      default: emoji("🍕"),
      deviceClasses: {
        pizza: { default: emoji("🍕") },
        coffee: { default: emoji("☕") },
        beer: { default: emoji("🍺") },
        wine: { default: emoji("🍷") },
        apple: { default: emoji("🍎") },
        cupcake: { default: emoji("🧁") },
        ice_cream: { default: emoji("🍦") },
        hamburger: { default: emoji("🍔") },
        noodles: { default: emoji("🍜") },
        rice: { default: emoji("🍚") },
        drumstick: { default: emoji("🍗") },
        candy_cane: { default: emoji("🍬") },
        cookie: { default: emoji("🍪") },
        cake: { default: emoji("🎂") },
        grapes: { default: emoji("🍇") },
        cherries: { default: emoji("🍒") },
        carrot: { default: emoji("🥕") },
        corn: { default: emoji("🌽") },
        chili: { default: emoji("🌶️") },
        muffin: { default: emoji("🧁") },
        egg: { default: emoji("🥚") },
        baguette: { default: emoji("🥖") },
        cheese: { default: emoji("🧀") },
      },
    },
    people: {
      default: emoji("👤"),
      deviceClasses: {
        person: { default: emoji("👤") },
        baby: { default: emoji("👶") },
        male: { default: emoji("👨") },
        female: { default: emoji("👩") },
        child: { default: emoji("🧒") },
        couple: { default: emoji("👫") },
        greeting: { default: emoji("🙋") },
        wheelchair: { default: emoji("♿") },
        run: { default: emoji("🏃") },
        walk: { default: emoji("🚶") },
        dance: { default: emoji("💃") },
        yoga: { default: emoji("🧘") },
        meditation: { default: emoji("🧘") },
        weight_lifter: { default: emoji("🏋️") },
        swim: { default: emoji("🏊") },
        hiking: { default: emoji("🥾") },
        bike: { default: emoji("🚴") },
      },
    },
    common: {
      default: emoji("🔔"),
      deviceClasses: {
        bell: { default: emoji("🔔") },
        clock: { default: emoji("🕐") },
        calendar: { default: emoji("📅") },
        email: { default: emoji("📧") },
        phone: { default: emoji("📞") },
        wifi: { default: emoji("📶") },
        bluetooth: { default: emoji("🔵") },
        music: { default: emoji("🎵") },
        image: { default: emoji("🖼️") },
        video: { default: emoji("📹") },
        book: { default: emoji("📖") },
        trash: { default: emoji("🗑️") },
        recycle: { default: emoji("♻️") },
        earth: { default: emoji("🌍") },
        map_marker: { default: emoji("📍") },
        flag: { default: emoji("🚩") },
        key: { default: emoji("🔑") },
        gift: { default: emoji("🎁") },
        tag: { default: emoji("🏷️") },
        basket: { default: emoji("🧺") },
        cart: { default: emoji("🛒") },
        search: { default: emoji("🔍") },
        settings: { default: emoji("⚙️") },
        info: { default: emoji("ℹ️") },
        help: { default: emoji("❓") },
        check_circle: { default: emoji("✅") },
        close_circle: { default: emoji("❌") },
        plus_circle: { default: emoji("⊕") },
        minus_circle: { default: emoji("⊖") },
      },
    },
    science: {
      default: emoji("⚛️"),
      deviceClasses: {
        atom: { default: emoji("⚛️") },
        dna: { default: emoji("🧬") },
        flask: { default: emoji("🧪") },
        microscope: { default: emoji("🔬") },
        telescope: { default: emoji("🔭") },
        rocket: { default: emoji("🚀") },
        satellite: { default: emoji("🛰️") },
        binoculars: { default: emoji("🔭") },
        compass: { default: emoji("🧭") },
        anchor: { default: emoji("⚓") },
        magnet: { default: emoji("🧲") },
      },
    },
    weather: {
      default: emoji("☀️"),
      deviceClasses: {
        sunny: { default: emoji("☀️") },
        night: { default: emoji("🌙") },
        cloudy: { default: emoji("☁️") },
        rainy: { default: emoji("🌧️") },
        snowy: { default: emoji("🌨️") },
        windy: { default: emoji("💨") },
        lightning: { default: emoji("⚡") },
        fog: { default: emoji("🌫️") },
        thermometer_high: { default: emoji("🌡️") },
        thermometer_low: { default: emoji("🥶") },
        island: { default: emoji("🏝️") },
        campfire: { default: emoji("🏕️") },
        tent: { default: emoji("⛺") },
        candle: { default: emoji("🕯️") },
        snowflake: { default: emoji("❄️") },
      },
    },
    fun: {
      default: emoji("😊"),
      deviceClasses: {
        emoticon: { default: emoji("😐") },
        happy: { default: emoji("😊") },
        sad: { default: emoji("😢") },
        cool: { default: emoji("😎") },
        robot: { default: emoji("🤖") },
        alien: { default: emoji("👽") },
        skull: { default: emoji("💀") },
        crown: { default: emoji("👑") },
        shield: { default: emoji("🛡️") },
        sword: { default: emoji("⚔️") },
        palette: { default: emoji("🎨") },
        brush: { default: emoji("🖌️") },
        spray_bottle: { default: emoji("🧴") },
        pencil: { default: emoji("✏️") },
        scissors: { default: emoji("✂️") },
      },
    },
    buildings: {
      default: emoji("🏠"),
      deviceClasses: {
        home: { default: emoji("🏠") },
        home_outline: { default: emoji("🏡") },
        floor_1: { default: emoji("1️⃣") },
        floor_2: { default: emoji("2️⃣") },
        floor_3: { default: emoji("3️⃣") },
        office: { default: emoji("🏢") },
        domain: { default: emoji("🏘️") },
        city: { default: emoji("🌆") },
        warehouse: { default: emoji("🏭") },
        barn: { default: emoji("🏚️") },
      },
    },
    medical: {
      default: emoji("💊"),
      deviceClasses: {
        pill: { default: emoji("💊") },
        hospital: { default: emoji("🏥") },
        medical_bag: { default: emoji("🧳") },
        stethoscope: { default: emoji("🩺") },
        needle: { default: emoji("💉") },
        virus: { default: emoji("🦠") },
      },
    },
    numbers: {
      default: emoji("1️⃣"),
      deviceClasses: {
        "0": { default: emoji("0️⃣") },
        "1": { default: emoji("1️⃣") },
        "2": { default: emoji("2️⃣") },
        "3": { default: emoji("3️⃣") },
        "4": { default: emoji("4️⃣") },
        "5": { default: emoji("5️⃣") },
        "6": { default: emoji("6️⃣") },
        "7": { default: emoji("7️⃣") },
        "8": { default: emoji("8️⃣") },
        "9": { default: emoji("9️⃣") },
        a: { default: emoji("🅰️") },
        b: { default: emoji("🅱️") },
        c: { default: emoji("©️") },
      },
    },
  },
};
