import {
  faLightbulb as faLightbulbReg,
  faWindowMaximize as faWindowMaximizeReg,
  faEye as faEyeReg,
  faBell as faBellReg,
  faSnowflake as faSnowflakeReg,
  faSun as faSunReg,
  faChartBar as faChartBarReg,
  faCirclePlay,
  faCirclePause,
  // Extra category regular icons
  faStar as faStarReg,
  faHeart as faHeartReg,
  faCircle as faCircleReg,
  faSquare as faSquareReg,
  faCompass as faCompassReg,
  faCalendar as faCalendarReg,
  faEnvelope as faEnvelopeReg,
  faMap as faMapReg,
  faFlag as faFlagReg,
  faGem as faGemReg,
  faBuilding as faBuildingReg,
  faUser as faUserReg,
  faFaceSmile as faFaceSmileReg,
  faFaceFrown as faFaceFrownReg,
  faFaceMeh as faFaceMehReg,
  faFaceGrinHearts as faFaceGrinHeartsReg,
  faFaceSurprise as faFaceSurpriseReg,
  faFaceLaugh as faFaceLaughReg,
  faFaceAngry as faFaceAngryReg,
  faFaceGrinWink as faFaceGrinWinkReg,
  faFaceRollingEyes as faFaceRollingEyesReg,
  faFaceGrimace as faFaceGrimaceReg,
  faFaceFlushed as faFaceFlushedReg,
  faFaceGrin as faFaceGrinReg,
  faHourglass as faHourglassReg,
  faImage as faImageReg,
  faImages as faImagesReg,
  faTrashCan as faTrashCanReg,
  faKeyboard as faKeyboardReg,
  faCopy as faCopyReg,
  faNewspaper as faNewspaperReg,
  faBookmark as faBookmarkReg,
  faLemon as faLemonReg,
  faMoon as faMoonReg,
  faCloud as faCloudReg,
  faFile as faFileReg,
  faPaperPlane as faPaperPlaneReg,
  faFolder as faFolderReg,
  faHospital as faHospitalReg,
  faStarHalfStroke as faStarHalfStrokeReg,
  faHouse as faHouseReg,
} from "@fortawesome/free-regular-svg-icons";
import {
  faBolt,
  faTemperatureHigh,
  faDroplet,
  faGaugeHigh,
  faPlug,
  faBatteryFull,
  faSmog,
  faWater,
  faPersonWalking,
  faDoorOpen,
  faDoorClosed,
  faFan,
  faCamera,
  faLock,
  faLockOpen,
  faFire,
  faArrowsRotate,
  faPowerOff,
  faWind,
  faShieldHalved,
  faTriangleExclamation,
  faUserGroup,
  faSatelliteDish,
  faTv,
  faToggleOn,
  faToggleOff,
  faBoltLightning,
  faMicrophone,
  faFilm,
  faFileCode,
  faGear,
  faCircleDot,
  faChair,
  faCouch,
  faBed,
  faSeedling,
  faToilet,
  faShower,
  faSink,
  faBath,
  faBook,
  // Extra category solid icons
  faTree,
  faLeaf,
  faUmbrellaBeach,
  faWaterLadder,
  faCar,
  faBicycle,
  faMotorcycle,
  faBus,
  faTrain,
  faPlane,
  faSailboat,
  faHelicopter,
  faGasPump,
  faWrench,
  faHammer,
  faScrewdriver,
  faToolbox,
  faRuler,
  faPenRuler,
  faShapes,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faAnglesUp,
  faAnglesDown,
  faDog,
  faCat,
  faFish,
  faDove,
  faPaw,
  faKiwiBird,
  faWorm,
  faFrog,
  faHippo,
  faOtter,
  faDragon,
  faSpider,
  faCow,
  faHorse,
  faPizzaSlice,
  faMugHot,
  faBeer,
  faWineGlass,
  faAppleWhole,
  faIceCream,
  faBurger,
  faDrumstickBite,
  faCookieBite,
  faCakeCandles,
  faCarrot,
  faPepperHot,
  faEgg,
  faCheese,
  faBreadSlice,
  faBacon,
  faBowlFood,
  faPersonRunning,
  faPersonHiking,
  faPersonSwimming,
  faPersonBiking,
  faPersonSkiing,
  faBaby,
  faChild,
  faWheelchair,
  faPhone,
  faWifi,
  faMusic,
  faTag,
  faCartShopping,
  faMagnifyingGlass,
  faCirclePlus,
  faCircleMinus,
  faCircleCheck,
  faCircleXmark,
  faAtom,
  faDna,
  faFlask,
  faMicroscope,
  faRocket,
  faSatellite,
  faBinoculars,
  faMagnet,
  faCloudRain,
  faCloudSun,
  faCloudBolt,
  faTemperatureLow,
  faSnowman,
  faCross,
  faRobot,
  faSkull,
  faCrown,
  faPalette,
  faPaintbrush,
  faScissors,
  faPencil,
  faHouseChimney,
  faWarehouse,
  faChurch,
  faMosque,
  faSchool,
  faGraduationCap,
  faPills,
  faSyringe,
  faStethoscope,
  faVirusSlash,
  faCapsules,
  fa0,
  fa1,
  fa2,
  fa3,
  fa4,
  fa5,
  fa6,
  fa7,
  fa8,
  fa9,
  faA,
  faB,
  faC,
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/free-solid-svg-icons";
import type { IconPack, IconEntry, IconStateStyle, IconData } from "../types";

function faIcon(def: IconDefinition): IconData {
  return {
    type: "path",
    value: def.icon[4] as string,
    viewBox: { w: def.icon[0], h: def.icon[1] },
  };
}

function fa(
  def: IconDefinition,
  opts?: { stateStyles?: Record<string, IconStateStyle>; defaultStyle?: IconStateStyle },
): IconEntry {
  return {
    icon: faIcon(def),
    defaultStyle: opts?.defaultStyle ?? { opacity: 1, colorMode: "static" },
    stateStyles: opts?.stateStyles ?? {
      on: { opacity: 1, colorMode: "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

function faLight(def: IconDefinition): IconEntry {
  return {
    icon: faIcon(def),
    defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
    stateStyles: {
      on: { opacity: 1, colorMode: "entity_rgb" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const faRegularPack: IconPack = {
  id: "fa-regular",
  name: "Font Awesome Light",
  description: "Font Awesome outline icons — clean, lighter weight",
  fallback: fa(faShieldHalved),
  domains: {
    light: {
      default: faLight(faLightbulbReg),
    },
    switch: {
      default: fa(faToggleOn),
      states: {
        on: fa(faToggleOn),
        off: fa(faToggleOff),
      },
    },
    cover: {
      default: fa(faWindowMaximizeReg),
    },
    sensor: {
      default: fa(faChartBarReg),
      deviceClasses: {
        temperature: { default: fa(faTemperatureHigh) },
        humidity: { default: fa(faDroplet) },
        pressure: { default: fa(faGaugeHigh) },
        power: { default: fa(faBolt) },
        energy: { default: fa(faBoltLightning) },
        battery: { default: fa(faBatteryFull) },
        illuminance: { default: fa(faSunReg) },
        carbon_dioxide: { default: fa(faSmog) },
        carbon_monoxide: { default: fa(faTriangleExclamation) },
        gas: { default: fa(faSmog) },
        moisture: { default: fa(faWater) },
        plug: { default: fa(faPlug) },
      },
    },
    binary_sensor: {
      default: fa(faEyeReg),
      deviceClasses: {
        motion: { default: fa(faPersonWalking) },
        door: {
          default: fa(faDoorClosed),
          states: { on: fa(faDoorOpen), off: fa(faDoorClosed) },
        },
        window: { default: fa(faWindowMaximizeReg) },
        vibration: { default: fa(faBellReg) },
        smoke: { default: fa(faFire) },
        occupancy: { default: fa(faUserGroup) },
        opening: {
          default: fa(faDoorClosed),
          states: { on: fa(faDoorOpen), off: fa(faDoorClosed) },
        },
        presence: { default: fa(faSatelliteDish) },
        problem: { default: fa(faTriangleExclamation) },
        safety: { default: fa(faShieldHalved) },
        sound: { default: fa(faMicrophone) },
      },
    },
    climate: {
      default: fa(faTemperatureHigh),
      states: {
        heat: fa(faFire),
        cool: fa(faSnowflakeReg),
        heat_cool: fa(faArrowsRotate),
        auto: fa(faArrowsRotate),
        dry: fa(faDroplet),
        fan_only: fa(faFan),
        off: fa(faPowerOff),
      },
    },
    fan: {
      default: fa(faFan),
      states: {
        on: fa(faFan),
        off: fa(faWind),
      },
    },
    camera: { default: fa(faCamera) },
    media_player: {
      default: fa(faTv),
      states: {
        playing: fa(faCirclePlay),
        paused: fa(faCirclePause),
      },
    },
    lock: {
      default: fa(faLock),
      states: {
        locked: fa(faLock),
        unlocked: fa(faLockOpen),
      },
    },
    scene: { default: fa(faFilm) },
    script: { default: fa(faFileCode) },
    automation: { default: fa(faGear) },
    button: { default: fa(faCircleDot) },
    furniture: {
      default: fa(faChair),
      deviceClasses: {
        sofa: { default: fa(faCouch) },
        bed: { default: fa(faBed) },
        table: { default: fa(faChair) },
        chair: { default: fa(faChair) },
        desk: { default: fa(faChair) },
        plant: { default: fa(faSeedling) },
        door: { default: fa(faDoorOpen) },
        window: { default: fa(faChair) },
        toilet: { default: fa(faToilet) },
        shower: { default: fa(faShower) },
        sink: { default: fa(faSink) },
        bathtub: { default: fa(faBath) },
        fridge: { default: fa(faChair) },
        oven: { default: fa(faChair) },
        dishwasher: { default: fa(faChair) },
        tv: { default: fa(faTv) },
        wardrobe: { default: fa(faChair) },
        bookshelf: { default: fa(faBook) },
      },
    },
    outdoor: {
      default: fa(faTree),
      deviceClasses: {
        tree: { default: fa(faTree) },
        leaf: { default: fa(faLeaf) },
        seedling: { default: fa(faSeedling) },
        umbrella: { default: fa(faUmbrellaBeach) },
        pool: { default: fa(faWaterLadder) },
        cloud: { default: fa(faCloudReg) },
        sun: { default: fa(faSunReg) },
        lemon: { default: fa(faLemonReg) },
      },
    },
    transport: {
      default: fa(faCar),
      deviceClasses: {
        car: { default: fa(faCar) },
        bicycle: { default: fa(faBicycle) },
        motorbike: { default: fa(faMotorcycle) },
        bus: { default: fa(faBus) },
        train: { default: fa(faTrain) },
        airplane: { default: fa(faPlane) },
        boat: { default: fa(faSailboat) },
        helicopter: { default: fa(faHelicopter) },
        gas_station: { default: fa(faGasPump) },
      },
    },
    tools: {
      default: fa(faWrench),
      deviceClasses: {
        wrench: { default: fa(faWrench) },
        hammer: { default: fa(faHammer) },
        screwdriver: { default: fa(faScrewdriver) },
        toolbox: { default: fa(faToolbox) },
        ruler: { default: fa(faRuler) },
        pencil_ruler: { default: fa(faPenRuler) },
      },
    },
    shapes: {
      default: fa(faShapes),
      deviceClasses: {
        circle: { default: fa(faCircleReg) },
        square: { default: fa(faSquareReg) },
        star: { default: fa(faStarReg) },
        star_half: { default: fa(faStarHalfStrokeReg) },
        heart: { default: fa(faHeartReg) },
        diamond: { default: fa(faGemReg) },
        cross: { default: fa(faCross) },
        check: { default: fa(faCircleCheck) },
        plus: { default: fa(faCirclePlus) },
        minus: { default: fa(faCircleMinus) },
      },
    },
    arrows: {
      default: fa(faArrowUp),
      deviceClasses: {
        up: { default: fa(faArrowUp) },
        down: { default: fa(faArrowDown) },
        left: { default: fa(faArrowLeft) },
        right: { default: fa(faArrowRight) },
        chevron_up: { default: fa(faChevronUp) },
        chevron_down: { default: fa(faChevronDown) },
        chevron_left: { default: fa(faChevronLeft) },
        chevron_right: { default: fa(faChevronRight) },
        angles_up: { default: fa(faAnglesUp) },
        angles_down: { default: fa(faAnglesDown) },
        rotate: { default: fa(faArrowsRotate) },
      },
    },
    animals: {
      default: fa(faPaw),
      deviceClasses: {
        dog: { default: fa(faDog) },
        cat: { default: fa(faCat) },
        fish: { default: fa(faFish) },
        bird: { default: fa(faDove) },
        paw: { default: fa(faPaw) },
        kiwi: { default: fa(faKiwiBird) },
        worm: { default: fa(faWorm) },
        frog: { default: fa(faFrog) },
        hippo: { default: fa(faHippo) },
        otter: { default: fa(faOtter) },
        dragon: { default: fa(faDragon) },
        spider: { default: fa(faSpider) },
        cow: { default: fa(faCow) },
        horse: { default: fa(faHorse) },
      },
    },
    food: {
      default: fa(faPizzaSlice),
      deviceClasses: {
        pizza: { default: fa(faPizzaSlice) },
        coffee: { default: fa(faMugHot) },
        beer: { default: fa(faBeer) },
        wine: { default: fa(faWineGlass) },
        apple: { default: fa(faAppleWhole) },
        ice_cream: { default: fa(faIceCream) },
        hamburger: { default: fa(faBurger) },
        drumstick: { default: fa(faDrumstickBite) },
        cookie: { default: fa(faCookieBite) },
        cake: { default: fa(faCakeCandles) },
        carrot: { default: fa(faCarrot) },
        chili: { default: fa(faPepperHot) },
        egg: { default: fa(faEgg) },
        cheese: { default: fa(faCheese) },
        bread: { default: fa(faBreadSlice) },
        bacon: { default: fa(faBacon) },
        bowl: { default: fa(faBowlFood) },
        lemon: { default: fa(faLemonReg) },
      },
    },
    people: {
      default: fa(faUserReg),
      deviceClasses: {
        person: { default: fa(faUserReg) },
        baby: { default: fa(faBaby) },
        child: { default: fa(faChild) },
        group: { default: fa(faUserGroup) },
        run: { default: fa(faPersonRunning) },
        walk: { default: fa(faPersonWalking) },
        hike: { default: fa(faPersonHiking) },
        swim: { default: fa(faPersonSwimming) },
        bike: { default: fa(faPersonBiking) },
        ski: { default: fa(faPersonSkiing) },
        wheelchair: { default: fa(faWheelchair) },
      },
    },
    common: {
      default: fa(faBellReg),
      deviceClasses: {
        bell: { default: fa(faBellReg) },
        clock: { default: fa(faHourglassReg) },
        calendar: { default: fa(faCalendarReg) },
        email: { default: fa(faEnvelopeReg) },
        phone: { default: fa(faPhone) },
        wifi: { default: fa(faWifi) },
        music: { default: fa(faMusic) },
        image: { default: fa(faImageReg) },
        images: { default: fa(faImagesReg) },
        book: { default: fa(faBook) },
        trash: { default: fa(faTrashCanReg) },
        map: { default: fa(faMapReg) },
        flag: { default: fa(faFlagReg) },
        key: { default: fa(faLock) },
        bookmark: { default: fa(faBookmarkReg) },
        tag: { default: fa(faTag) },
        cart: { default: fa(faCartShopping) },
        search: { default: fa(faMagnifyingGlass) },
        settings: { default: fa(faGear) },
        copy: { default: fa(faCopyReg) },
        file: { default: fa(faFileReg) },
        folder: { default: fa(faFolderReg) },
        paper_plane: { default: fa(faPaperPlaneReg) },
        newspaper: { default: fa(faNewspaperReg) },
        keyboard: { default: fa(faKeyboardReg) },
        check_circle: { default: fa(faCircleCheck) },
        close_circle: { default: fa(faCircleXmark) },
        plus_circle: { default: fa(faCirclePlus) },
        minus_circle: { default: fa(faCircleMinus) },
      },
    },
    science: {
      default: fa(faAtom),
      deviceClasses: {
        atom: { default: fa(faAtom) },
        dna: { default: fa(faDna) },
        flask: { default: fa(faFlask) },
        microscope: { default: fa(faMicroscope) },
        rocket: { default: fa(faRocket) },
        satellite: { default: fa(faSatellite) },
        binoculars: { default: fa(faBinoculars) },
        compass: { default: fa(faCompassReg) },
        magnet: { default: fa(faMagnet) },
      },
    },
    weather: {
      default: fa(faSunReg),
      deviceClasses: {
        sunny: { default: fa(faSunReg) },
        night: { default: fa(faMoonReg) },
        cloudy: { default: fa(faCloudReg) },
        rainy: { default: fa(faCloudRain) },
        snowy: { default: fa(faSnowflakeReg) },
        windy: { default: fa(faWind) },
        lightning: { default: fa(faCloudBolt) },
        cloud_sun: { default: fa(faCloudSun) },
        thermometer_high: { default: fa(faTemperatureHigh) },
        thermometer_low: { default: fa(faTemperatureLow) },
        snowman: { default: fa(faSnowman) },
      },
    },
    fun: {
      default: fa(faFaceSmileReg),
      deviceClasses: {
        smile: { default: fa(faFaceSmileReg) },
        grin: { default: fa(faFaceGrinReg) },
        laugh: { default: fa(faFaceLaughReg) },
        wink: { default: fa(faFaceGrinWinkReg) },
        hearts: { default: fa(faFaceGrinHeartsReg) },
        surprise: { default: fa(faFaceSurpriseReg) },
        frown: { default: fa(faFaceFrownReg) },
        angry: { default: fa(faFaceAngryReg) },
        meh: { default: fa(faFaceMehReg) },
        rolling_eyes: { default: fa(faFaceRollingEyesReg) },
        grimace: { default: fa(faFaceGrimaceReg) },
        flushed: { default: fa(faFaceFlushedReg) },
        robot: { default: fa(faRobot) },
        skull: { default: fa(faSkull) },
        crown: { default: fa(faCrown) },
        palette: { default: fa(faPalette) },
        brush: { default: fa(faPaintbrush) },
        pencil: { default: fa(faPencil) },
        scissors: { default: fa(faScissors) },
      },
    },
    buildings: {
      default: fa(faHouseReg),
      deviceClasses: {
        home: { default: fa(faHouseReg) },
        home_chimney: { default: fa(faHouseChimney) },
        building: { default: fa(faBuildingReg) },
        warehouse: { default: fa(faWarehouse) },
        church: { default: fa(faChurch) },
        mosque: { default: fa(faMosque) },
        school: { default: fa(faSchool) },
        graduation: { default: fa(faGraduationCap) },
        hospital: { default: fa(faHospitalReg) },
      },
    },
    medical: {
      default: fa(faPills),
      deviceClasses: {
        pill: { default: fa(faPills) },
        hospital: { default: fa(faHospitalReg) },
        stethoscope: { default: fa(faStethoscope) },
        syringe: { default: fa(faSyringe) },
        virus: { default: fa(faVirusSlash) },
        capsules: { default: fa(faCapsules) },
      },
    },
    numbers: {
      default: fa(fa1),
      deviceClasses: {
        "0": { default: fa(fa0) },
        "1": { default: fa(fa1) },
        "2": { default: fa(fa2) },
        "3": { default: fa(fa3) },
        "4": { default: fa(fa4) },
        "5": { default: fa(fa5) },
        "6": { default: fa(fa6) },
        "7": { default: fa(fa7) },
        "8": { default: fa(fa8) },
        "9": { default: fa(fa9) },
        a: { default: fa(faA) },
        b: { default: fa(faB) },
        c: { default: fa(faC) },
      },
    },
  },
};
