import {
  faLightbulb,
  faBolt,
  faWindowMaximize,
  faChartBar,
  faTemperatureHigh,
  faDroplet,
  faGaugeHigh,
  faPlug,
  faBatteryFull,
  faSun,
  faSmog,
  faWater,
  faPersonWalking,
  faDoorOpen,
  faDoorClosed,
  faFan,
  faCamera,
  faPlay,
  faPause,
  faLock,
  faLockOpen,
  faFire,
  faSnowflake,
  faArrowsRotate,
  faPowerOff,
  faWind,
  faShieldHalved,
  faTriangleExclamation,
  faUserGroup,
  faSatelliteDish,
  faTv,
  faToggleOn,
  faToggleOff,
  faBoltLightning,
  faBell,
  faEye,
  faMicrophone,
  faFilm,
  faFileCode,
  faGear,
  faCircleDot,
  faChair,
  faCouch,
  faBed,
  faSeedling,
  faToilet,
  faShower,
  faSink,
  faBath,
  faBook,
  // outdoor
  faTree,
  faMountain,
  faUmbrella,
  faSwimmingPool,
  faLeaf,
  faCloud,
  faUmbrellaBeach,
  faMountainSun,
  faCampground,
  faTent,
  faTreeCity,
  faPersonSwimming,
  // transport
  faCar,
  faBicycle,
  faMotorcycle,
  faBus,
  faTrain,
  faPlane,
  faShip,
  faHelicopter,
  faGasPump,
  faParking,
  faTruck,
  faTaxi,
  faTrainSubway,
  // tools
  faWrench,
  faHammer,
  faScrewdriver,
  faToolbox,
  faRuler,
  faPencil,
  faTape,
  faPaintRoller,
  faBrush,
  // shapes
  faCircle,
  faSquare,
  faStar,
  faHeart,
  faDiamond,
  faPlus,
  faMinus,
  faCheck,
  faXmark,
  // arrows
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faAnglesUp,
  faAnglesDown,
  faCaretUp,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  // animals
  faDog,
  faCat,
  faFish,
  faDove,
  faPaw,
  faSpider,
  faHorse,
  faCrow,
  faFrog,
  faOtter,
  faKiwiBird,
  faShrimp,
  faWorm,
  faLocust,
  faBugs,
  faMosquito,
  // food
  faPizzaSlice,
  faMugHot,
  faBeerMugEmpty,
  faWineGlass,
  faAppleWhole,
  faIceCream,
  faBurger,
  faCookieBite,
  faCandyCane,
  faCarrot,
  faLemon,
  faPepperHot,
  faEgg,
  faBowlFood,
  faBowlRice,
  faDrumstickBite,
  faWheatAwn,
  faCheese,
  faBacon,
  faHotdog,
  // people
  faUser,
  faBaby,
  faPerson,
  faPersonDress,
  faChildDress,
  faPeopleGroup,
  faPersonRunning,
  faPersonHiking,
  faPersonBiking,
  faChild,
  faUserNurse,
  faUserDoctor,
  faUserAstronaut,
  faUserSecret,
  faUserNinja,
  faPersonCane,
  faPersonPraying,
  faUserTie,
  faUserGraduate,
  // common
  faClock,
  faCalendar,
  faEnvelope,
  faPhone,
  faWifi,
  faMusic,
  faImage,
  faVideo,
  faTrash,
  faRecycle,
  faEarthAmericas,
  faLocationDot,
  faFlag,
  faKey,
  faGift,
  faTag,
  faBasketShopping,
  faCartShopping,
  faMagnifyingGlass,
  faCircleInfo,
  faCircleQuestion,
  faCircleCheck,
  faCircleXmark,
  // science
  faAtom,
  faDna,
  faFlask,
  faMicroscope,
  faRocket,
  faSatellite,
  faCompass,
  faAnchor,
  faMagnet,
  faBiohazard,
  faRadiation,
  faVial,
  // weather
  faMoon,
  faCloudRain,
  faCloudSun,
  faCloudMoon,
  faCloudBolt,
  faRainbow,
  faTornado,
  faHurricane,
  faTemperatureLow,
  faTemperatureHalf,
  faCloudSunRain,
  faCloudShowersHeavy,
  faCloudMeatball,
  // fun
  faFaceSmile,
  faFaceGrinBeam,
  faFaceSadTear,
  faFaceGrinSquint,
  faRobot,
  faSkull,
  faCrown,
  faShield,
  faPalette,
  faPaintBrush,
  faSprayCan,
  faScissors,
  faFaceLaugh,
  faFaceMeh,
  faFaceAngry,
  faFaceSurprise,
  faGhost,
  faMask,
  faHatWizard,
  faWandMagic,
  faDice,
  faGamepad,
  faPuzzlePiece,
  faChess,
  // buildings
  faHouse,
  faBuilding,
  faCity,
  faWarehouse,
  faChurch,
  faSchool,
  faHospital,
  faIndustry,
  faStore,
  faLandmark,
  faMosque,
  faMonument,
  faSynagogue,
  // medical
  faPills,
  faSuitcaseMedical,
  faStethoscope,
  faSyringe,
  faVirus,
  faBandage,
  faNotesMedical,
  faPrescription,
  faHeartPulse,
  faCapsules,
  faTablets,
  faLungs,
  faBone,
  faBrain,
  faTooth,
  faXRay,
  // numbers
  fa0,
  fa1,
  fa2,
  fa3,
  fa4,
  fa5,
  fa6,
  fa7,
  fa8,
  fa9,
  faA,
  faB,
  faC,
  faD,
  faE,
  faF,
  faG,
  faH,
  faI,
  faJ,
  faK,
  faL,
  faM,
  faN,
  faO,
  faP,
  faQ,
  faR,
  faS,
  faT,
  faU,
  faV,
  faW,
  faX,
  faY,
  faZ,
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/free-solid-svg-icons";
import type { IconPack, IconEntry, IconStateStyle, IconData } from "../types";

/** Extract path data + viewBox from a Font Awesome icon */
function faIcon(def: IconDefinition): IconData {
  return {
    type: "path",
    value: def.icon[4] as string,
    viewBox: { w: def.icon[0], h: def.icon[1] },
  };
}

function fa(
  def: IconDefinition,
  opts?: { stateStyles?: Record<string, IconStateStyle>; defaultStyle?: IconStateStyle },
): IconEntry {
  return {
    icon: faIcon(def),
    defaultStyle: opts?.defaultStyle ?? { opacity: 1, colorMode: "static" },
    stateStyles: opts?.stateStyles ?? {
      on: { opacity: 1, colorMode: "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

function faLight(def: IconDefinition): IconEntry {
  return {
    icon: faIcon(def),
    defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
    stateStyles: {
      on: { opacity: 1, colorMode: "entity_rgb" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const faSolidPack: IconPack = {
  id: "fa-solid",
  name: "Font Awesome",
  description: "Font Awesome solid icons — bold, recognizable shapes",
  fallback: fa(faShieldHalved),
  domains: {
    light: {
      default: faLight(faLightbulb),
    },
    switch: {
      default: fa(faToggleOn),
      states: {
        on: fa(faToggleOn),
        off: fa(faToggleOff),
      },
    },
    cover: {
      default: fa(faWindowMaximize),
    },
    sensor: {
      default: fa(faChartBar),
      deviceClasses: {
        temperature: { default: fa(faTemperatureHigh) },
        humidity: { default: fa(faDroplet) },
        pressure: { default: fa(faGaugeHigh) },
        power: { default: fa(faBolt) },
        energy: { default: fa(faBoltLightning) },
        battery: { default: fa(faBatteryFull) },
        illuminance: { default: fa(faSun) },
        carbon_dioxide: { default: fa(faSmog) },
        carbon_monoxide: { default: fa(faTriangleExclamation) },
        gas: { default: fa(faSmog) },
        moisture: { default: fa(faWater) },
        plug: { default: fa(faPlug) },
      },
    },
    binary_sensor: {
      default: fa(faEye),
      deviceClasses: {
        motion: { default: fa(faPersonWalking) },
        door: {
          default: fa(faDoorClosed),
          states: { on: fa(faDoorOpen), off: fa(faDoorClosed) },
        },
        window: { default: fa(faWindowMaximize) },
        vibration: { default: fa(faBell) },
        smoke: { default: fa(faFire) },
        occupancy: { default: fa(faUserGroup) },
        opening: {
          default: fa(faDoorClosed),
          states: { on: fa(faDoorOpen), off: fa(faDoorClosed) },
        },
        presence: { default: fa(faSatelliteDish) },
        problem: { default: fa(faTriangleExclamation) },
        safety: { default: fa(faShieldHalved) },
        sound: { default: fa(faMicrophone) },
      },
    },
    climate: {
      default: fa(faTemperatureHigh),
      states: {
        heat: fa(faFire),
        cool: fa(faSnowflake),
        heat_cool: fa(faArrowsRotate),
        auto: fa(faArrowsRotate),
        dry: fa(faDroplet),
        fan_only: fa(faFan),
        off: fa(faPowerOff),
      },
    },
    fan: {
      default: fa(faFan),
      states: {
        on: fa(faFan),
        off: fa(faWind),
      },
    },
    camera: { default: fa(faCamera) },
    media_player: {
      default: fa(faTv),
      states: {
        playing: fa(faPlay),
        paused: fa(faPause),
      },
    },
    lock: {
      default: fa(faLock),
      states: {
        locked: fa(faLock),
        unlocked: fa(faLockOpen),
      },
    },
    scene: { default: fa(faFilm) },
    script: { default: fa(faFileCode) },
    automation: { default: fa(faGear) },
    button: { default: fa(faCircleDot) },
    furniture: {
      default: fa(faChair),
      deviceClasses: {
        sofa: { default: fa(faCouch) },
        bed: { default: fa(faBed) },
        table: { default: fa(faChair) },
        chair: { default: fa(faChair) },
        desk: { default: fa(faChair) },
        plant: { default: fa(faSeedling) },
        door: { default: fa(faDoorOpen) },
        window: { default: fa(faChair) },
        toilet: { default: fa(faToilet) },
        shower: { default: fa(faShower) },
        sink: { default: fa(faSink) },
        bathtub: { default: fa(faBath) },
        fridge: { default: fa(faChair) },
        oven: { default: fa(faChair) },
        dishwasher: { default: fa(faChair) },
        tv: { default: fa(faTv) },
        wardrobe: { default: fa(faChair) },
        bookshelf: { default: fa(faBook) },
      },
    },
    outdoor: {
      default: fa(faTree),
      deviceClasses: {
        tree: { default: fa(faTree) },
        mountain: { default: fa(faMountain) },
        mountain_sun: { default: fa(faMountainSun) },
        umbrella: { default: fa(faUmbrella) },
        umbrella_beach: { default: fa(faUmbrellaBeach) },
        pool: { default: fa(faSwimmingPool) },
        swimming: { default: fa(faPersonSwimming) },
        leaf: { default: fa(faLeaf) },
        seedling: { default: fa(faSeedling) },
        cloud: { default: fa(faCloud) },
        water: { default: fa(faWater) },
        fire: { default: fa(faFire) },
        campground: { default: fa(faCampground) },
        tent: { default: fa(faTent) },
        tree_city: { default: fa(faTreeCity) },
      },
    },
    transport: {
      default: fa(faCar),
      deviceClasses: {
        car: { default: fa(faCar) },
        bicycle: { default: fa(faBicycle) },
        motorcycle: { default: fa(faMotorcycle) },
        bus: { default: fa(faBus) },
        train: { default: fa(faTrain) },
        subway: { default: fa(faTrainSubway) },
        plane: { default: fa(faPlane) },
        ship: { default: fa(faShip) },
        helicopter: { default: fa(faHelicopter) },
        gas_pump: { default: fa(faGasPump) },
        parking: { default: fa(faParking) },
        truck: { default: fa(faTruck) },
        taxi: { default: fa(faTaxi) },
      },
    },
    tools: {
      default: fa(faWrench),
      deviceClasses: {
        wrench: { default: fa(faWrench) },
        hammer: { default: fa(faHammer) },
        screwdriver: { default: fa(faScrewdriver) },
        toolbox: { default: fa(faToolbox) },
        ruler: { default: fa(faRuler) },
        pencil: { default: fa(faPencil) },
        tape: { default: fa(faTape) },
        paint_roller: { default: fa(faPaintRoller) },
        brush: { default: fa(faBrush) },
      },
    },
    shapes: {
      default: fa(faCircle),
      deviceClasses: {
        circle: { default: fa(faCircle) },
        square: { default: fa(faSquare) },
        star: { default: fa(faStar) },
        heart: { default: fa(faHeart) },
        diamond: { default: fa(faDiamond) },
        plus: { default: fa(faPlus) },
        minus: { default: fa(faMinus) },
        check: { default: fa(faCheck) },
        xmark: { default: fa(faXmark) },
      },
    },
    arrows: {
      default: fa(faArrowUp),
      deviceClasses: {
        arrow_up: { default: fa(faArrowUp) },
        arrow_down: { default: fa(faArrowDown) },
        arrow_left: { default: fa(faArrowLeft) },
        arrow_right: { default: fa(faArrowRight) },
        chevron_up: { default: fa(faChevronUp) },
        chevron_down: { default: fa(faChevronDown) },
        chevron_left: { default: fa(faChevronLeft) },
        chevron_right: { default: fa(faChevronRight) },
        angles_up: { default: fa(faAnglesUp) },
        angles_down: { default: fa(faAnglesDown) },
        caret_up: { default: fa(faCaretUp) },
        caret_down: { default: fa(faCaretDown) },
        caret_left: { default: fa(faCaretLeft) },
        caret_right: { default: fa(faCaretRight) },
      },
    },
    animals: {
      default: fa(faPaw),
      deviceClasses: {
        dog: { default: fa(faDog) },
        cat: { default: fa(faCat) },
        fish: { default: fa(faFish) },
        dove: { default: fa(faDove) },
        paw: { default: fa(faPaw) },
        spider: { default: fa(faSpider) },
        horse: { default: fa(faHorse) },
        crow: { default: fa(faCrow) },
        frog: { default: fa(faFrog) },
        otter: { default: fa(faOtter) },
        kiwi_bird: { default: fa(faKiwiBird) },
        shrimp: { default: fa(faShrimp) },
        worm: { default: fa(faWorm) },
        locust: { default: fa(faLocust) },
        bugs: { default: fa(faBugs) },
        mosquito: { default: fa(faMosquito) },
      },
    },
    food: {
      default: fa(faBowlFood),
      deviceClasses: {
        pizza: { default: fa(faPizzaSlice) },
        mug: { default: fa(faMugHot) },
        beer: { default: fa(faBeerMugEmpty) },
        wine: { default: fa(faWineGlass) },
        apple: { default: fa(faAppleWhole) },
        ice_cream: { default: fa(faIceCream) },
        burger: { default: fa(faBurger) },
        cookie: { default: fa(faCookieBite) },
        candy_cane: { default: fa(faCandyCane) },
        carrot: { default: fa(faCarrot) },
        lemon: { default: fa(faLemon) },
        pepper: { default: fa(faPepperHot) },
        egg: { default: fa(faEgg) },
        bowl_food: { default: fa(faBowlFood) },
        bowl_rice: { default: fa(faBowlRice) },
        drumstick: { default: fa(faDrumstickBite) },
        wheat: { default: fa(faWheatAwn) },
        cheese: { default: fa(faCheese) },
        bacon: { default: fa(faBacon) },
        hotdog: { default: fa(faHotdog) },
      },
    },
    people: {
      default: fa(faUser),
      deviceClasses: {
        user: { default: fa(faUser) },
        baby: { default: fa(faBaby) },
        person: { default: fa(faPerson) },
        person_dress: { default: fa(faPersonDress) },
        child_dress: { default: fa(faChildDress) },
        people_group: { default: fa(faPeopleGroup) },
        person_walking: { default: fa(faPersonWalking) },
        person_running: { default: fa(faPersonRunning) },
        person_swimming: { default: fa(faPersonSwimming) },
        person_hiking: { default: fa(faPersonHiking) },
        person_biking: { default: fa(faPersonBiking) },
        child: { default: fa(faChild) },
        user_nurse: { default: fa(faUserNurse) },
        user_doctor: { default: fa(faUserDoctor) },
        user_astronaut: { default: fa(faUserAstronaut) },
        user_secret: { default: fa(faUserSecret) },
        user_ninja: { default: fa(faUserNinja) },
        person_cane: { default: fa(faPersonCane) },
        person_praying: { default: fa(faPersonPraying) },
        user_tie: { default: fa(faUserTie) },
        user_graduate: { default: fa(faUserGraduate) },
      },
    },
    common: {
      default: fa(faBell),
      deviceClasses: {
        bell: { default: fa(faBell) },
        clock: { default: fa(faClock) },
        calendar: { default: fa(faCalendar) },
        envelope: { default: fa(faEnvelope) },
        phone: { default: fa(faPhone) },
        wifi: { default: fa(faWifi) },
        music: { default: fa(faMusic) },
        image: { default: fa(faImage) },
        video: { default: fa(faVideo) },
        book: { default: fa(faBook) },
        trash: { default: fa(faTrash) },
        recycle: { default: fa(faRecycle) },
        earth: { default: fa(faEarthAmericas) },
        location: { default: fa(faLocationDot) },
        flag: { default: fa(faFlag) },
        key: { default: fa(faKey) },
        gift: { default: fa(faGift) },
        tag: { default: fa(faTag) },
        basket: { default: fa(faBasketShopping) },
        cart: { default: fa(faCartShopping) },
        search: { default: fa(faMagnifyingGlass) },
        gear: { default: fa(faGear) },
        info: { default: fa(faCircleInfo) },
        question: { default: fa(faCircleQuestion) },
        check: { default: fa(faCircleCheck) },
        xmark: { default: fa(faCircleXmark) },
      },
    },
    science: {
      default: fa(faAtom),
      deviceClasses: {
        atom: { default: fa(faAtom) },
        dna: { default: fa(faDna) },
        flask: { default: fa(faFlask) },
        microscope: { default: fa(faMicroscope) },
        rocket: { default: fa(faRocket) },
        satellite: { default: fa(faSatellite) },
        compass: { default: fa(faCompass) },
        anchor: { default: fa(faAnchor) },
        magnet: { default: fa(faMagnet) },
        biohazard: { default: fa(faBiohazard) },
        radiation: { default: fa(faRadiation) },
        vial: { default: fa(faVial) },
      },
    },
    weather: {
      default: fa(faSun),
      deviceClasses: {
        sun: { default: fa(faSun) },
        moon: { default: fa(faMoon) },
        cloud: { default: fa(faCloud) },
        cloud_rain: { default: fa(faCloudRain) },
        cloud_sun: { default: fa(faCloudSun) },
        cloud_moon: { default: fa(faCloudMoon) },
        cloud_bolt: { default: fa(faCloudBolt) },
        cloud_sun_rain: { default: fa(faCloudSunRain) },
        cloud_showers_heavy: { default: fa(faCloudShowersHeavy) },
        cloud_meatball: { default: fa(faCloudMeatball) },
        snowflake: { default: fa(faSnowflake) },
        wind: { default: fa(faWind) },
        bolt: { default: fa(faBolt) },
        smog: { default: fa(faSmog) },
        temperature_high: { default: fa(faTemperatureHigh) },
        temperature_low: { default: fa(faTemperatureLow) },
        temperature_half: { default: fa(faTemperatureHalf) },
        rainbow: { default: fa(faRainbow) },
        tornado: { default: fa(faTornado) },
        hurricane: { default: fa(faHurricane) },
      },
    },
    fun: {
      default: fa(faFaceSmile),
      deviceClasses: {
        smile: { default: fa(faFaceSmile) },
        grin_beam: { default: fa(faFaceGrinBeam) },
        sad_tear: { default: fa(faFaceSadTear) },
        grin_squint: { default: fa(faFaceGrinSquint) },
        laugh: { default: fa(faFaceLaugh) },
        meh: { default: fa(faFaceMeh) },
        angry: { default: fa(faFaceAngry) },
        surprise: { default: fa(faFaceSurprise) },
        robot: { default: fa(faRobot) },
        skull: { default: fa(faSkull) },
        crown: { default: fa(faCrown) },
        shield: { default: fa(faShield) },
        palette: { default: fa(faPalette) },
        paint_brush: { default: fa(faPaintBrush) },
        spray_can: { default: fa(faSprayCan) },
        pencil: { default: fa(faPencil) },
        scissors: { default: fa(faScissors) },
        ghost: { default: fa(faGhost) },
        mask: { default: fa(faMask) },
        hat_wizard: { default: fa(faHatWizard) },
        wand_magic: { default: fa(faWandMagic) },
        dice: { default: fa(faDice) },
        gamepad: { default: fa(faGamepad) },
        puzzle: { default: fa(faPuzzlePiece) },
        chess: { default: fa(faChess) },
      },
    },
    buildings: {
      default: fa(faHouse),
      deviceClasses: {
        house: { default: fa(faHouse) },
        building: { default: fa(faBuilding) },
        city: { default: fa(faCity) },
        warehouse: { default: fa(faWarehouse) },
        church: { default: fa(faChurch) },
        school: { default: fa(faSchool) },
        hospital: { default: fa(faHospital) },
        industry: { default: fa(faIndustry) },
        store: { default: fa(faStore) },
        landmark: { default: fa(faLandmark) },
        mosque: { default: fa(faMosque) },
        monument: { default: fa(faMonument) },
        synagogue: { default: fa(faSynagogue) },
      },
    },
    medical: {
      default: fa(faSuitcaseMedical),
      deviceClasses: {
        pills: { default: fa(faPills) },
        hospital: { default: fa(faHospital) },
        suitcase_medical: { default: fa(faSuitcaseMedical) },
        stethoscope: { default: fa(faStethoscope) },
        syringe: { default: fa(faSyringe) },
        virus: { default: fa(faVirus) },
        bandage: { default: fa(faBandage) },
        notes_medical: { default: fa(faNotesMedical) },
        prescription: { default: fa(faPrescription) },
        heart_pulse: { default: fa(faHeartPulse) },
        capsules: { default: fa(faCapsules) },
        tablets: { default: fa(faTablets) },
        lungs: { default: fa(faLungs) },
        bone: { default: fa(faBone) },
        brain: { default: fa(faBrain) },
        tooth: { default: fa(faTooth) },
        xray: { default: fa(faXRay) },
      },
    },
    numbers: {
      default: fa(fa0),
      deviceClasses: {
        "0": { default: fa(fa0) },
        "1": { default: fa(fa1) },
        "2": { default: fa(fa2) },
        "3": { default: fa(fa3) },
        "4": { default: fa(fa4) },
        "5": { default: fa(fa5) },
        "6": { default: fa(fa6) },
        "7": { default: fa(fa7) },
        "8": { default: fa(fa8) },
        "9": { default: fa(fa9) },
        a: { default: fa(faA) },
        b: { default: fa(faB) },
        c: { default: fa(faC) },
        d: { default: fa(faD) },
        e: { default: fa(faE) },
        f: { default: fa(faF) },
        g: { default: fa(faG) },
        h: { default: fa(faH) },
        i: { default: fa(faI) },
        j: { default: fa(faJ) },
        k: { default: fa(faK) },
        l: { default: fa(faL) },
        m: { default: fa(faM) },
        n: { default: fa(faN) },
        o: { default: fa(faO) },
        p: { default: fa(faP) },
        q: { default: fa(faQ) },
        r: { default: fa(faR) },
        s: { default: fa(faS) },
        t: { default: fa(faT) },
        u: { default: fa(faU) },
        v: { default: fa(faV) },
        w: { default: fa(faW) },
        x: { default: fa(faX) },
        y: { default: fa(faY) },
        z: { default: fa(faZ) },
      },
    },
  },
};
