import {
  mdiLightbulbGroup,
  mdiLightbulbGroupOff,
  mdiPowerSocketEu,
  mdiRollerShade,
  mdiRollerShadeClosed,
  mdiChartBarStacked,
  mdiThermometerLines,
  mdiWaterPercent,
  mdiGaugeFull,
  mdiFlash,
  mdiBatteryHigh,
  mdiWeatherSunny,
  mdiMoleculeCo2,
  mdiAlertCircleOutline,
  mdiGasCylinder,
  mdiWaterOutline,
  mdiPowerPlugOutline,
  mdiMotionSensor,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiWindowOpenVariant,
  mdiWindowClosedVariant,
  mdiVibrate,
  mdiSmokeDetectorVariant,
  mdiAccountGroupOutline,
  mdiAccessPointNetwork,
  mdiShieldOutline,
  mdiVolumeHigh,
  mdiFan,
  mdiFanOff,
  mdiWebcam,
  mdiWebcamOff,
  mdiTelevision,
  mdiTelevisionOff,
  mdiPlay,
  mdiPause,
  mdiLockOutline,
  mdiLockOpenOutline,
  mdiFire,
  mdiSnowflake,
  mdiSync,
  mdiPower,
  mdiHexagonOutline,
  mdiLightningBolt,
  mdiAirConditioner,
  mdiGarageOpen,
  mdiGarage,
  mdiMovieOpen,
  mdiScriptText,
  mdiRobotHappy,
  mdiGestureTap,
  mdiSofa,
  mdiBed,
  mdiTable,
  mdiChairRolling,
  mdiDesk,
  mdiFlower,
  mdiToilet,
  mdiShower,
  mdiWaterPump,
  mdiBathtub,
  mdiFridge,
  mdiStove,
  mdiDishwasher,
  mdiWardrobe,
  mdiBookshelf,
} from "@mdi/js";
import type { IconPack, IconEntry, IconStateStyle } from "../types";

function path(
  d: string,
  opts?: { stateStyles?: Record<string, IconStateStyle>; defaultStyle?: IconStateStyle },
): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: opts?.defaultStyle ?? { opacity: 1, colorMode: "static" },
    stateStyles: opts?.stateStyles ?? {
      on: { opacity: 1, colorMode: "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

function lightPath(d: string): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
    stateStyles: {
      on: { opacity: 1, colorMode: "entity_rgb" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const mdiTechPack: IconPack = {
  id: "mdi-tech",
  name: "Smart Tech",
  description: "Tech-forward — light groups, smart plugs, roller shades, TVs",
  fallback: path(mdiHexagonOutline),
  domains: {
    light: {
      default: lightPath(mdiLightbulbGroup),
      states: {
        off: lightPath(mdiLightbulbGroupOff),
      },
    },
    switch: { default: path(mdiPowerSocketEu) },
    cover: {
      default: path(mdiRollerShadeClosed),
      states: {
        open: path(mdiRollerShade),
        opening: path(mdiRollerShade),
        closed: path(mdiRollerShadeClosed),
        closing: path(mdiRollerShadeClosed),
      },
      deviceClasses: {
        garage: {
          default: path(mdiGarage),
          states: { open: path(mdiGarageOpen), closed: path(mdiGarage) },
        },
      },
    },
    sensor: {
      default: path(mdiChartBarStacked),
      deviceClasses: {
        temperature: { default: path(mdiThermometerLines) },
        humidity: { default: path(mdiWaterPercent) },
        pressure: { default: path(mdiGaugeFull) },
        power: { default: path(mdiFlash) },
        energy: { default: path(mdiLightningBolt) },
        battery: { default: path(mdiBatteryHigh) },
        illuminance: { default: path(mdiWeatherSunny) },
        carbon_dioxide: { default: path(mdiMoleculeCo2) },
        carbon_monoxide: { default: path(mdiAlertCircleOutline) },
        gas: { default: path(mdiGasCylinder) },
        moisture: { default: path(mdiWaterOutline) },
        plug: { default: path(mdiPowerPlugOutline) },
      },
    },
    binary_sensor: {
      default: path(mdiAlertCircleOutline),
      deviceClasses: {
        motion: { default: path(mdiMotionSensor) },
        door: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        window: {
          default: path(mdiWindowClosedVariant),
          states: { on: path(mdiWindowOpenVariant), off: path(mdiWindowClosedVariant) },
        },
        vibration: { default: path(mdiVibrate) },
        smoke: { default: path(mdiSmokeDetectorVariant) },
        occupancy: { default: path(mdiAccountGroupOutline) },
        opening: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        presence: { default: path(mdiAccessPointNetwork) },
        problem: { default: path(mdiAlertCircleOutline) },
        safety: { default: path(mdiShieldOutline) },
        sound: { default: path(mdiVolumeHigh) },
      },
    },
    climate: {
      default: path(mdiAirConditioner),
      states: {
        heat: path(mdiFire),
        cool: path(mdiSnowflake),
        heat_cool: path(mdiSync),
        auto: path(mdiSync),
        dry: path(mdiWaterOutline),
        fan_only: path(mdiFan),
        off: path(mdiPower),
      },
    },
    fan: {
      default: path(mdiFan),
      states: {
        on: path(mdiFan),
        off: path(mdiFanOff),
      },
    },
    camera: {
      default: path(mdiWebcam),
      states: {
        off: path(mdiWebcamOff),
      },
    },
    media_player: {
      default: path(mdiTelevision),
      states: {
        playing: path(mdiPlay),
        paused: path(mdiPause),
        off: path(mdiTelevisionOff),
      },
    },
    lock: {
      default: path(mdiLockOutline),
      states: {
        locked: path(mdiLockOutline),
        unlocked: path(mdiLockOpenOutline),
      },
    },
    scene: { default: path(mdiMovieOpen) },
    script: { default: path(mdiScriptText) },
    automation: { default: path(mdiRobotHappy) },
    button: { default: path(mdiGestureTap) },
    furniture: {
      default: path(mdiChairRolling),
      deviceClasses: {
        sofa: { default: path(mdiSofa) },
        bed: { default: path(mdiBed) },
        table: { default: path(mdiTable) },
        chair: { default: path(mdiChairRolling) },
        desk: { default: path(mdiDesk) },
        plant: { default: path(mdiFlower) },
        door: { default: path(mdiDoorOpen) },
        window: { default: path(mdiWindowOpenVariant) },
        toilet: { default: path(mdiToilet) },
        shower: { default: path(mdiShower) },
        sink: { default: path(mdiWaterPump) },
        bathtub: { default: path(mdiBathtub) },
        fridge: { default: path(mdiFridge) },
        oven: { default: path(mdiStove) },
        dishwasher: { default: path(mdiDishwasher) },
        tv: { default: path(mdiTelevision) },
        wardrobe: { default: path(mdiWardrobe) },
        bookshelf: { default: path(mdiBookshelf) },
      },
    },
  },
};
