import {
  mdiLamp,
  mdiLampOutline,
  mdiToggleSwitchVariant,
  mdiToggleSwitchVariantOff,
  mdiCurtains,
  mdiCurtainsClosed,
  mdiChartBar,
  mdiHomeThermometerOutline,
  mdiWaterPercent,
  mdiGauge,
  mdiFlash,
  mdiBatteryHigh,
  mdiWeatherSunny,
  mdiMoleculeCo2,
  mdiAlertCircle,
  mdiGasCylinder,
  mdiWater,
  mdiPowerPlug,
  mdiMotionSensor,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiWindowOpenVariant,
  mdiWindowClosedVariant,
  mdiVibrate,
  mdiSmokeDetectorVariant,
  mdiAccountGroup,
  mdiAccessPoint,
  mdiShieldCheck,
  mdiVolumeHigh,
  mdiAirPurifier,
  mdiAirPurifierOff,
  mdiWebcam,
  mdiCast,
  mdiCastConnected,
  mdiPause,
  mdiShieldLock,
  mdiShieldLockOpen,
  mdiRadiator,
  mdiSnowflake,
  mdiSync,
  mdiWaterOutline,
  mdiPower,
  mdiHexagonOutline,
  mdiLightningBolt,
  mdiHeatWave,
  mdiMovieOpen,
  mdiScriptText,
  mdiRobotHappy,
  mdiGestureTap,
  mdiSofa,
  mdiBed,
  mdiTable,
  mdiChairRolling,
  mdiDesk,
  mdiFlower,
  mdiToilet,
  mdiShower,
  mdiWaterPump,
  mdiBathtub,
  mdiFridge,
  mdiStove,
  mdiDishwasher,
  mdiTelevision,
  mdiWardrobe,
  mdiBookshelf,
} from "@mdi/js";
import type { IconPack, IconEntry, IconStateStyle } from "../types";

function path(
  d: string,
  opts?: { stateStyles?: Record<string, IconStateStyle>; defaultStyle?: IconStateStyle },
): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: opts?.defaultStyle ?? { opacity: 1, colorMode: "static" },
    stateStyles: opts?.stateStyles ?? {
      on: { opacity: 1, colorMode: "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

function lightPath(d: string): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
    stateStyles: {
      on: { opacity: 1, colorMode: "entity_rgb" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const mdiCozyPack: IconPack = {
  id: "mdi-cozy",
  name: "Cozy Home",
  description: "Warm, cozy icons — table lamps, curtains, radiators, cast devices",
  fallback: path(mdiHexagonOutline),
  domains: {
    light: {
      default: lightPath(mdiLamp),
      states: {
        off: lightPath(mdiLampOutline),
      },
    },
    switch: {
      default: path(mdiToggleSwitchVariant),
      states: {
        on: path(mdiToggleSwitchVariant),
        off: path(mdiToggleSwitchVariantOff),
      },
    },
    cover: {
      default: path(mdiCurtainsClosed),
      states: {
        open: path(mdiCurtains),
        opening: path(mdiCurtains),
        closed: path(mdiCurtainsClosed),
        closing: path(mdiCurtainsClosed),
      },
    },
    sensor: {
      default: path(mdiChartBar),
      deviceClasses: {
        temperature: { default: path(mdiHomeThermometerOutline) },
        humidity: { default: path(mdiWaterPercent) },
        pressure: { default: path(mdiGauge) },
        power: { default: path(mdiFlash) },
        energy: { default: path(mdiLightningBolt) },
        battery: { default: path(mdiBatteryHigh) },
        illuminance: { default: path(mdiWeatherSunny) },
        carbon_dioxide: { default: path(mdiMoleculeCo2) },
        carbon_monoxide: { default: path(mdiAlertCircle) },
        gas: { default: path(mdiGasCylinder) },
        moisture: { default: path(mdiWater) },
        plug: { default: path(mdiPowerPlug) },
      },
    },
    binary_sensor: {
      default: path(mdiAlertCircle),
      deviceClasses: {
        motion: { default: path(mdiMotionSensor) },
        door: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        window: {
          default: path(mdiWindowClosedVariant),
          states: { on: path(mdiWindowOpenVariant), off: path(mdiWindowClosedVariant) },
        },
        vibration: { default: path(mdiVibrate) },
        smoke: { default: path(mdiSmokeDetectorVariant) },
        occupancy: { default: path(mdiAccountGroup) },
        opening: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        presence: { default: path(mdiAccessPoint) },
        problem: { default: path(mdiAlertCircle) },
        safety: { default: path(mdiShieldCheck) },
        sound: { default: path(mdiVolumeHigh) },
      },
    },
    climate: {
      default: path(mdiRadiator),
      states: {
        heat: path(mdiHeatWave),
        cool: path(mdiSnowflake),
        heat_cool: path(mdiSync),
        auto: path(mdiSync),
        dry: path(mdiWaterOutline),
        fan_only: path(mdiAirPurifier),
        off: path(mdiPower),
      },
    },
    fan: {
      default: path(mdiAirPurifier),
      states: {
        on: path(mdiAirPurifier),
        off: path(mdiAirPurifierOff),
      },
    },
    camera: { default: path(mdiWebcam) },
    media_player: {
      default: path(mdiCast),
      states: {
        playing: path(mdiCastConnected),
        paused: path(mdiPause),
      },
    },
    lock: {
      default: path(mdiShieldLock),
      states: {
        locked: path(mdiShieldLock),
        unlocked: path(mdiShieldLockOpen),
      },
    },
    scene: { default: path(mdiMovieOpen) },
    script: { default: path(mdiScriptText) },
    automation: { default: path(mdiRobotHappy) },
    button: { default: path(mdiGestureTap) },
    furniture: {
      default: path(mdiChairRolling),
      deviceClasses: {
        sofa: { default: path(mdiSofa) },
        bed: { default: path(mdiBed) },
        table: { default: path(mdiTable) },
        chair: { default: path(mdiChairRolling) },
        desk: { default: path(mdiDesk) },
        plant: { default: path(mdiFlower) },
        door: { default: path(mdiDoorOpen) },
        window: { default: path(mdiWindowOpenVariant) },
        toilet: { default: path(mdiToilet) },
        shower: { default: path(mdiShower) },
        sink: { default: path(mdiWaterPump) },
        bathtub: { default: path(mdiBathtub) },
        fridge: { default: path(mdiFridge) },
        oven: { default: path(mdiStove) },
        dishwasher: { default: path(mdiDishwasher) },
        tv: { default: path(mdiTelevision) },
        wardrobe: { default: path(mdiWardrobe) },
        bookshelf: { default: path(mdiBookshelf) },
      },
    },
  },
};
