import {
  mdiLightbulbOutline,
  mdiLightbulbOffOutline,
  mdiToggleSwitchOutline,
  mdiToggleSwitchOffOutline,
  mdiWindowShutter,
  mdiWindowShutterOpen,
  mdiChartBarStacked,
  mdiThermometerLines,
  mdiWaterPercent,
  mdiGaugeEmpty,
  mdiFlashOutline,
  mdiBatteryOutline,
  mdiWeatherSunny,
  mdiMoleculeCo2,
  mdiAlertCircleOutline,
  mdiGasCylinder,
  mdiWaterOutline,
  mdiPowerPlugOutline,
  mdiMotionSensor,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiWindowOpenVariant,
  mdiWindowClosedVariant,
  mdiVibrate,
  mdiSmokeDetectorOutline,
  mdiAccountGroupOutline,
  mdiAccessPoint,
  mdiShieldOutline,
  mdiVolumeHigh,
  mdiFan,
  mdiCameraOutline,
  mdiSpeaker,
  mdiPlayOutline,
  mdiPause,
  mdiLockOutline,
  mdiLockOpenOutline,
  mdiFire,
  mdiSnowflake,
  mdiSync,
  mdiPower,
  mdiHexagonOutline,
  mdiLightningBolt,
  mdiMovieOpen,
  mdiScriptText,
  mdiRobotHappy,
  mdiGestureTap,
  mdiSofa,
  mdiBed,
  mdiTable,
  mdiChairRolling,
  mdiDesk,
  mdiFlower,
  mdiToilet,
  mdiShower,
  mdiWaterPump,
  mdiBathtub,
  mdiFridge,
  mdiStove,
  mdiDishwasher,
  mdiTelevision,
  mdiWardrobe,
  mdiBookshelf,
} from "@mdi/js";
import type { IconPack, IconEntry, IconStateStyle } from "../types";

function path(
  d: string,
  opts?: { stateStyles?: Record<string, IconStateStyle>; defaultStyle?: IconStateStyle },
): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: opts?.defaultStyle ?? { opacity: 1, colorMode: "static" },
    stateStyles: opts?.stateStyles ?? {
      on: { opacity: 1, colorMode: "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

function lightPath(d: string): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
    stateStyles: {
      on: { opacity: 1, colorMode: "entity_rgb" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const mdiOutlinePack: IconPack = {
  id: "mdi-outline",
  name: "Material Outline",
  description: "Lighter outline-style Material Design Icons",
  fallback: path(mdiHexagonOutline),
  domains: {
    light: {
      default: lightPath(mdiLightbulbOutline),
      states: {
        off: lightPath(mdiLightbulbOffOutline),
      },
    },
    switch: {
      default: path(mdiToggleSwitchOutline),
      states: {
        on: path(mdiToggleSwitchOutline),
        off: path(mdiToggleSwitchOffOutline),
      },
    },
    cover: {
      default: path(mdiWindowShutter),
      states: {
        open: path(mdiWindowShutterOpen),
        opening: path(mdiWindowShutterOpen),
        closed: path(mdiWindowShutter),
        closing: path(mdiWindowShutter),
      },
    },
    sensor: {
      default: path(mdiChartBarStacked),
      deviceClasses: {
        temperature: { default: path(mdiThermometerLines) },
        humidity: { default: path(mdiWaterPercent) },
        pressure: { default: path(mdiGaugeEmpty) },
        power: { default: path(mdiFlashOutline) },
        energy: { default: path(mdiLightningBolt) },
        battery: { default: path(mdiBatteryOutline) },
        illuminance: { default: path(mdiWeatherSunny) },
        carbon_dioxide: { default: path(mdiMoleculeCo2) },
        carbon_monoxide: { default: path(mdiAlertCircleOutline) },
        gas: { default: path(mdiGasCylinder) },
        moisture: { default: path(mdiWaterOutline) },
        plug: { default: path(mdiPowerPlugOutline) },
      },
    },
    binary_sensor: {
      default: path(mdiAlertCircleOutline),
      deviceClasses: {
        motion: { default: path(mdiMotionSensor) },
        door: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        window: {
          default: path(mdiWindowClosedVariant),
          states: { on: path(mdiWindowOpenVariant), off: path(mdiWindowClosedVariant) },
        },
        vibration: { default: path(mdiVibrate) },
        smoke: { default: path(mdiSmokeDetectorOutline) },
        occupancy: { default: path(mdiAccountGroupOutline) },
        opening: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        presence: { default: path(mdiAccessPoint) },
        problem: { default: path(mdiAlertCircleOutline) },
        safety: { default: path(mdiShieldOutline) },
        sound: { default: path(mdiVolumeHigh) },
      },
    },
    climate: {
      default: path(mdiThermometerLines),
      states: {
        heat: path(mdiFire),
        cool: path(mdiSnowflake),
        heat_cool: path(mdiSync),
        auto: path(mdiSync),
        dry: path(mdiWaterOutline),
        fan_only: path(mdiFan),
        off: path(mdiPower),
      },
    },
    fan: { default: path(mdiFan) },
    camera: { default: path(mdiCameraOutline) },
    media_player: {
      default: path(mdiSpeaker),
      states: {
        playing: path(mdiPlayOutline),
        paused: path(mdiPause),
      },
    },
    lock: {
      default: path(mdiLockOutline),
      states: {
        locked: path(mdiLockOutline),
        unlocked: path(mdiLockOpenOutline),
      },
    },
    scene: { default: path(mdiMovieOpen) },
    script: { default: path(mdiScriptText) },
    automation: { default: path(mdiRobotHappy) },
    button: { default: path(mdiGestureTap) },
    furniture: {
      default: path(mdiChairRolling),
      deviceClasses: {
        sofa: { default: path(mdiSofa) },
        bed: { default: path(mdiBed) },
        table: { default: path(mdiTable) },
        chair: { default: path(mdiChairRolling) },
        desk: { default: path(mdiDesk) },
        plant: { default: path(mdiFlower) },
        door: { default: path(mdiDoorOpen) },
        window: { default: path(mdiWindowOpenVariant) },
        toilet: { default: path(mdiToilet) },
        shower: { default: path(mdiShower) },
        sink: { default: path(mdiWaterPump) },
        bathtub: { default: path(mdiBathtub) },
        fridge: { default: path(mdiFridge) },
        oven: { default: path(mdiStove) },
        dishwasher: { default: path(mdiDishwasher) },
        tv: { default: path(mdiTelevision) },
        wardrobe: { default: path(mdiWardrobe) },
        bookshelf: { default: path(mdiBookshelf) },
      },
    },
  },
};
