import {
  mdiCeilingLight,
  mdiLightbulbOff,
  mdiLightSwitch,
  mdiWindowShutter,
  mdiWindowShutterOpen,
  mdiChartBar,
  mdiHomeThermometer,
  mdiWaterPercent,
  mdiGauge,
  mdiFlash,
  mdiBatteryHigh,
  mdiWeatherSunny,
  mdiMoleculeCo2,
  mdiAlertCircle,
  mdiGasCylinder,
  mdiWater,
  mdiPowerPlug,
  mdiMotionSensor,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiWindowOpenVariant,
  mdiWindowClosedVariant,
  mdiVibrate,
  mdiSmokeDetectorVariant,
  mdiAccountGroup,
  mdiAccessPoint,
  mdiShieldCheck,
  mdiVolumeHigh,
  mdiFan,
  mdiCamera,
  mdiSpeaker,
  mdiPlay,
  mdiPause,
  mdiLock,
  mdiLockOpen,
  mdiFire,
  mdiSnowflake,
  mdiSync,
  mdiWaterOutline,
  mdiPower,
  mdiHexagonOutline,
  mdiLightningBolt,
  mdiFloorLamp,
  mdiWallSconce,
  mdiLedStrip,
  mdiHomeLightbulbOutline,
  mdiMovieOpen,
  mdiScriptText,
  mdiRobotHappy,
  mdiGestureTap,
  mdiSofa,
  mdiBed,
  mdiTable,
  mdiChairRolling,
  mdiDesk,
  mdiFlower,
  mdiToilet,
  mdiShower,
  mdiWaterPump,
  mdiBathtub,
  mdiFridge,
  mdiStove,
  mdiDishwasher,
  mdiTelevision,
  mdiWardrobe,
  mdiBookshelf,
  mdiDeskLamp,
  mdiWallSconceFlat,
  mdiChandelier,
  mdiLightFloodDown,
  mdiSpotlightBeam,
  mdiStringLights,
  mdiTrackLight,
  mdiCoachLamp,
  mdiLamp,
  mdiOutdoorLamp,
  mdiVanityLight,
  mdiMicrowave,
  mdiWashingMachine,
  mdiTumbleDryer,
  mdiRobotVacuum,
  mdiCoffeeMaker,
  mdiBlender,
  mdiToaster,
  mdiToasterOven,
  mdiFireplace,
  mdiRadiator,
  mdiAirConditioner,
  mdiCeilingFan,
  mdiCurtains,
  mdiIron,
  mdiHairDryer,
  mdiLaptop,
  mdiCellphone,
  mdiTablet,
  mdiRouter,
  mdiPrinter,
  mdiKeyboard,
  mdiMouse,
  mdiMonitor,
  mdiGamepad,
  mdiHeadphones,
  mdiProjector,
  mdiCameraWireless,
  mdiSpeakerWireless,
  mdiNas,
  mdiServerNetwork,
  mdiHarddisk,
  mdiUsbFlashDrive,
  mdiSmartCard,
  mdiTree,
  mdiPineTree,
  mdiFence,
  mdiGarage,
  mdiPool,
  mdiGrill,
  mdiUmbrellaBeach,
  mdiCactus,
  mdiSprout,
  mdiGrass,
  mdiLeaf,
  mdiFlowerTulip,
  mdiBarley,
  mdiMushroom,
  mdiCompost,
  mdiCar,
  mdiBicycle,
  mdiMotorbike,
  mdiBus,
  mdiTrain,
  mdiAirplane,
  mdiSailBoat,
  mdiHelicopter,
  mdiScooter,
  mdiScooterElectric,
  mdiCarElectric,
  mdiEvStation,
  mdiGasStation,
  mdiParking,
  mdiWrench,
  mdiHammer,
  mdiScrewdriver,
  mdiHandSaw,
  mdiToolbox,
  mdiTapeMeasure,
  mdiRuler,
  mdiPencilRuler,
  mdiCircle,
  mdiCircleOutline,
  mdiSquare,
  mdiSquareOutline,
  mdiTriangle,
  mdiTriangleOutline,
  mdiStar,
  mdiStarOutline,
  mdiHeart,
  mdiHeartOutline,
  mdiCardsDiamond,
  mdiCardsDiamondOutline,
  mdiHexagon,
  mdiOctagon,
  mdiOctagonOutline,
  mdiPentagon,
  mdiPentagonOutline,
  mdiDecagram,
  mdiDecagramOutline,
  mdiCross,
  mdiClose,
  mdiPlus,
  mdiMinus,
  mdiCheck,
  mdiArrowUp,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUpBold,
  mdiArrowDownBold,
  mdiArrowLeftBold,
  mdiArrowRightBold,
  mdiChevronUp,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiDog,
  mdiCat,
  mdiFish,
  mdiBird,
  mdiPaw,
  mdiBee,
  mdiTurtle,
  mdiRabbit,
  mdiDuck,
  mdiOwl,
  mdiButterfly,
  mdiHorseshoe,
  mdiSnake,
  mdiSpider,
  mdiPizza,
  mdiCoffee,
  mdiBeer,
  mdiGlassWine,
  mdiFoodApple,
  mdiCupcake,
  mdiIceCream,
  mdiHamburger,
  mdiNoodles,
  mdiRice,
  mdiFoodDrumstick,
  mdiCandycane,
  mdiCookie,
  mdiCakeVariant,
  mdiFruitGrapes,
  mdiFruitCherries,
  mdiCarrot,
  mdiCorn,
  mdiChiliMild,
  mdiMuffin,
  mdiEgg,
  mdiBaguette,
  mdiCheese,
  mdiAccount,
  mdiBaby,
  mdiHumanMale,
  mdiHumanFemale,
  mdiHumanChild,
  mdiHumanMaleFemale,
  mdiHumanGreeting,
  mdiHumanWheelchair,
  mdiRun,
  mdiWalk,
  mdiHumanFemaleDance,
  mdiYoga,
  mdiMeditation,
  mdiWeightLifter,
  mdiSwim,
  mdiHiking,
  mdiBike,
  mdiBell,
  mdiClock,
  mdiCalendar,
  mdiEmail,
  mdiPhone,
  mdiWifi,
  mdiBluetooth,
  mdiMusic,
  mdiImage,
  mdiVideo,
  mdiBook,
  mdiTrashCan,
  mdiRecycle,
  mdiEarth,
  mdiMapMarker,
  mdiFlag,
  mdiKey,
  mdiGift,
  mdiTag,
  mdiBasket,
  mdiCart,
  mdiMagnify,
  mdiCog,
  mdiInformation,
  mdiHelp,
  mdiCheckCircle,
  mdiCloseCircle,
  mdiPlusCircle,
  mdiMinusCircle,
  mdiAtom,
  mdiDna,
  mdiFlask,
  mdiMicroscope,
  mdiTelescope,
  mdiRocket,
  mdiSatelliteVariant,
  mdiBinoculars,
  mdiCompass,
  mdiAnchor,
  mdiMagnet,
  mdiIsland,
  mdiCampfire,
  mdiTent,
  mdiCandle,
  mdiWeatherNight,
  mdiWeatherCloudy,
  mdiWeatherRainy,
  mdiWeatherSnowy,
  mdiWeatherWindy,
  mdiWeatherLightning,
  mdiWeatherFog,
  mdiThermometerHigh,
  mdiThermometerLow,
  mdiEmoticon,
  mdiEmoticonHappy,
  mdiEmoticonSad,
  mdiEmoticonCool,
  mdiRobot,
  mdiAlien,
  mdiSkull,
  mdiCrown,
  mdiShield,
  mdiSword,
  mdiPalette,
  mdiBrush,
  mdiSprayBottle,
  mdiPencil,
  mdiContentCut,
  mdiHome,
  mdiHomeOutline,
  mdiHomeFloor1,
  mdiHomeFloor2,
  mdiHomeFloor3,
  mdiOfficeBuilding,
  mdiDomain,
  mdiCity,
  mdiWarehouse,
  mdiBarn,
  mdiPill,
  mdiHospitalBox,
  mdiMedicalBag,
  mdiStethoscope,
  mdiNeedle,
  mdiVirusOutline,
  mdiNumeric0,
  mdiNumeric1,
  mdiNumeric2,
  mdiNumeric3,
  mdiNumeric4,
  mdiNumeric5,
  mdiNumeric6,
  mdiNumeric7,
  mdiNumeric8,
  mdiNumeric9,
  mdiAlphaA,
  mdiAlphaB,
  mdiAlphaC,
} from "@mdi/js";
import type { IconPack, IconEntry, IconStateStyle } from "../types";

function path(
  d: string,
  opts?: { stateStyles?: Record<string, IconStateStyle>; defaultStyle?: IconStateStyle },
): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: opts?.defaultStyle ?? { opacity: 1, colorMode: "static" },
    stateStyles: opts?.stateStyles ?? {
      on: { opacity: 1, colorMode: "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

function lightPath(d: string): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
    stateStyles: {
      on: { opacity: 1, colorMode: "entity_rgb" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const mdiHomePack: IconPack = {
  id: "mdi-home",
  name: "Home Style",
  description: "Home-focused icons — ceiling lights, floor lamps, wall sconces",
  fallback: path(mdiHexagonOutline),
  domains: {
    light: {
      default: lightPath(mdiCeilingLight),
      states: {
        off: lightPath(mdiLightbulbOff),
      },
      deviceClasses: {
        floor_lamp: { default: lightPath(mdiFloorLamp) },
        wall_light: { default: lightPath(mdiWallSconce) },
        led_strip: { default: lightPath(mdiLedStrip) },
      },
    },
    switch: { default: path(mdiLightSwitch) },
    cover: {
      default: path(mdiWindowShutter),
      states: {
        open: path(mdiWindowShutterOpen),
        opening: path(mdiWindowShutterOpen),
        closed: path(mdiWindowShutter),
        closing: path(mdiWindowShutter),
      },
    },
    sensor: {
      default: path(mdiChartBar),
      deviceClasses: {
        temperature: { default: path(mdiHomeThermometer) },
        humidity: { default: path(mdiWaterPercent) },
        pressure: { default: path(mdiGauge) },
        power: { default: path(mdiFlash) },
        energy: { default: path(mdiLightningBolt) },
        battery: { default: path(mdiBatteryHigh) },
        illuminance: { default: path(mdiWeatherSunny) },
        carbon_dioxide: { default: path(mdiMoleculeCo2) },
        carbon_monoxide: { default: path(mdiAlertCircle) },
        gas: { default: path(mdiGasCylinder) },
        moisture: { default: path(mdiWater) },
        plug: { default: path(mdiPowerPlug) },
      },
    },
    binary_sensor: {
      default: path(mdiHomeLightbulbOutline),
      deviceClasses: {
        motion: { default: path(mdiMotionSensor) },
        door: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        window: {
          default: path(mdiWindowClosedVariant),
          states: { on: path(mdiWindowOpenVariant), off: path(mdiWindowClosedVariant) },
        },
        vibration: { default: path(mdiVibrate) },
        smoke: { default: path(mdiSmokeDetectorVariant) },
        occupancy: { default: path(mdiAccountGroup) },
        opening: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        presence: { default: path(mdiAccessPoint) },
        problem: { default: path(mdiAlertCircle) },
        safety: { default: path(mdiShieldCheck) },
        sound: { default: path(mdiVolumeHigh) },
      },
    },
    climate: {
      default: path(mdiHomeThermometer),
      states: {
        heat: path(mdiFire),
        cool: path(mdiSnowflake),
        heat_cool: path(mdiSync),
        auto: path(mdiSync),
        dry: path(mdiWaterOutline),
        fan_only: path(mdiFan),
        off: path(mdiPower),
      },
    },
    fan: { default: path(mdiFan) },
    camera: { default: path(mdiCamera) },
    media_player: {
      default: path(mdiSpeaker),
      states: {
        playing: path(mdiPlay),
        paused: path(mdiPause),
      },
    },
    lock: {
      default: path(mdiLock),
      states: {
        locked: path(mdiLock),
        unlocked: path(mdiLockOpen),
      },
    },
    scene: { default: path(mdiMovieOpen) },
    script: { default: path(mdiScriptText) },
    automation: { default: path(mdiRobotHappy) },
    button: { default: path(mdiGestureTap) },
    furniture: {
      default: path(mdiChairRolling),
      deviceClasses: {
        sofa: { default: path(mdiSofa) },
        bed: { default: path(mdiBed) },
        table: { default: path(mdiTable) },
        chair: { default: path(mdiChairRolling) },
        desk: { default: path(mdiDesk) },
        plant: { default: path(mdiFlower) },
        door: { default: path(mdiDoorOpen) },
        window: { default: path(mdiWindowOpenVariant) },
        toilet: { default: path(mdiToilet) },
        shower: { default: path(mdiShower) },
        sink: { default: path(mdiWaterPump) },
        bathtub: { default: path(mdiBathtub) },
        fridge: { default: path(mdiFridge) },
        oven: { default: path(mdiStove) },
        dishwasher: { default: path(mdiDishwasher) },
        tv: { default: path(mdiTelevision) },
        wardrobe: { default: path(mdiWardrobe) },
        bookshelf: { default: path(mdiBookshelf) },
      },
    },
    /* ──────── Extra categories ──────── */
    lighting: {
      default: path(mdiCeilingLight),
      deviceClasses: {
        ceiling_light: { default: path(mdiCeilingLight) },
        floor_lamp: { default: path(mdiFloorLamp) },
        desk_lamp: { default: path(mdiDeskLamp) },
        wall_sconce: { default: path(mdiWallSconceFlat) },
        chandelier: { default: path(mdiChandelier) },
        led_strip: { default: path(mdiLedStrip) },
        flood_light: { default: path(mdiLightFloodDown) },
        spotlight: { default: path(mdiSpotlightBeam) },
        string_lights: { default: path(mdiStringLights) },
        track_light: { default: path(mdiTrackLight) },
        coach_lamp: { default: path(mdiCoachLamp) },
        lamp: { default: path(mdiLamp) },
        outdoor_lamp: { default: path(mdiOutdoorLamp) },
        vanity_light: { default: path(mdiVanityLight) },
      },
    },
    appliance: {
      default: path(mdiMicrowave),
      deviceClasses: {
        microwave: { default: path(mdiMicrowave) },
        washing_machine: { default: path(mdiWashingMachine) },
        tumble_dryer: { default: path(mdiTumbleDryer) },
        robot_vacuum: { default: path(mdiRobotVacuum) },
        coffee_maker: { default: path(mdiCoffeeMaker) },
        blender: { default: path(mdiBlender) },
        toaster: { default: path(mdiToaster) },
        toaster_oven: { default: path(mdiToasterOven) },
        fireplace: { default: path(mdiFireplace) },
        radiator: { default: path(mdiRadiator) },
        air_conditioner: { default: path(mdiAirConditioner) },
        ceiling_fan: { default: path(mdiCeilingFan) },
        curtains: { default: path(mdiCurtains) },
        iron: { default: path(mdiIron) },
        hair_dryer: { default: path(mdiHairDryer) },
      },
    },
    electronics: {
      default: path(mdiLaptop),
      deviceClasses: {
        laptop: { default: path(mdiLaptop) },
        cellphone: { default: path(mdiCellphone) },
        tablet: { default: path(mdiTablet) },
        router: { default: path(mdiRouter) },
        printer: { default: path(mdiPrinter) },
        keyboard: { default: path(mdiKeyboard) },
        mouse: { default: path(mdiMouse) },
        monitor: { default: path(mdiMonitor) },
        gamepad: { default: path(mdiGamepad) },
        headphones: { default: path(mdiHeadphones) },
        projector: { default: path(mdiProjector) },
        wireless_camera: { default: path(mdiCameraWireless) },
        wireless_speaker: { default: path(mdiSpeakerWireless) },
        nas: { default: path(mdiNas) },
        server: { default: path(mdiServerNetwork) },
        hard_disk: { default: path(mdiHarddisk) },
        usb_drive: { default: path(mdiUsbFlashDrive) },
        smart_card: { default: path(mdiSmartCard) },
      },
    },
    outdoor: {
      default: path(mdiTree),
      deviceClasses: {
        tree: { default: path(mdiTree) },
        pine_tree: { default: path(mdiPineTree) },
        fence: { default: path(mdiFence) },
        garage: { default: path(mdiGarage) },
        pool: { default: path(mdiPool) },
        grill: { default: path(mdiGrill) },
        umbrella: { default: path(mdiUmbrellaBeach) },
        cactus: { default: path(mdiCactus) },
        sprout: { default: path(mdiSprout) },
        grass: { default: path(mdiGrass) },
        leaf: { default: path(mdiLeaf) },
        tulip: { default: path(mdiFlowerTulip) },
        barley: { default: path(mdiBarley) },
        mushroom: { default: path(mdiMushroom) },
        compost: { default: path(mdiCompost) },
      },
    },
    transport: {
      default: path(mdiCar),
      deviceClasses: {
        car: { default: path(mdiCar) },
        bicycle: { default: path(mdiBicycle) },
        motorbike: { default: path(mdiMotorbike) },
        bus: { default: path(mdiBus) },
        train: { default: path(mdiTrain) },
        airplane: { default: path(mdiAirplane) },
        boat: { default: path(mdiSailBoat) },
        helicopter: { default: path(mdiHelicopter) },
        scooter: { default: path(mdiScooter) },
        electric_scooter: { default: path(mdiScooterElectric) },
        electric_car: { default: path(mdiCarElectric) },
        ev_station: { default: path(mdiEvStation) },
        gas_station: { default: path(mdiGasStation) },
        parking: { default: path(mdiParking) },
      },
    },
    tools: {
      default: path(mdiWrench),
      deviceClasses: {
        wrench: { default: path(mdiWrench) },
        hammer: { default: path(mdiHammer) },
        screwdriver: { default: path(mdiScrewdriver) },
        saw: { default: path(mdiHandSaw) },
        toolbox: { default: path(mdiToolbox) },
        tape_measure: { default: path(mdiTapeMeasure) },
        ruler: { default: path(mdiRuler) },
        pencil_ruler: { default: path(mdiPencilRuler) },
      },
    },
    shapes: {
      default: path(mdiCircle),
      deviceClasses: {
        circle: { default: path(mdiCircle) },
        circle_outline: { default: path(mdiCircleOutline) },
        square: { default: path(mdiSquare) },
        square_outline: { default: path(mdiSquareOutline) },
        triangle: { default: path(mdiTriangle) },
        triangle_outline: { default: path(mdiTriangleOutline) },
        star: { default: path(mdiStar) },
        star_outline: { default: path(mdiStarOutline) },
        heart: { default: path(mdiHeart) },
        heart_outline: { default: path(mdiHeartOutline) },
        diamond: { default: path(mdiCardsDiamond) },
        diamond_outline: { default: path(mdiCardsDiamondOutline) },
        hexagon: { default: path(mdiHexagon) },
        octagon: { default: path(mdiOctagon) },
        octagon_outline: { default: path(mdiOctagonOutline) },
        pentagon: { default: path(mdiPentagon) },
        pentagon_outline: { default: path(mdiPentagonOutline) },
        decagram: { default: path(mdiDecagram) },
        decagram_outline: { default: path(mdiDecagramOutline) },
        cross: { default: path(mdiCross) },
        close: { default: path(mdiClose) },
        plus: { default: path(mdiPlus) },
        minus: { default: path(mdiMinus) },
        check: { default: path(mdiCheck) },
      },
    },
    arrows: {
      default: path(mdiArrowUp),
      deviceClasses: {
        up: { default: path(mdiArrowUp) },
        down: { default: path(mdiArrowDown) },
        left: { default: path(mdiArrowLeft) },
        right: { default: path(mdiArrowRight) },
        up_bold: { default: path(mdiArrowUpBold) },
        down_bold: { default: path(mdiArrowDownBold) },
        left_bold: { default: path(mdiArrowLeftBold) },
        right_bold: { default: path(mdiArrowRightBold) },
        chevron_up: { default: path(mdiChevronUp) },
        chevron_down: { default: path(mdiChevronDown) },
        chevron_left: { default: path(mdiChevronLeft) },
        chevron_right: { default: path(mdiChevronRight) },
      },
    },
    animals: {
      default: path(mdiPaw),
      deviceClasses: {
        dog: { default: path(mdiDog) },
        cat: { default: path(mdiCat) },
        fish: { default: path(mdiFish) },
        bird: { default: path(mdiBird) },
        paw: { default: path(mdiPaw) },
        bee: { default: path(mdiBee) },
        turtle: { default: path(mdiTurtle) },
        rabbit: { default: path(mdiRabbit) },
        duck: { default: path(mdiDuck) },
        owl: { default: path(mdiOwl) },
        butterfly: { default: path(mdiButterfly) },
        horseshoe: { default: path(mdiHorseshoe) },
        snake: { default: path(mdiSnake) },
        spider: { default: path(mdiSpider) },
      },
    },
    food: {
      default: path(mdiPizza),
      deviceClasses: {
        pizza: { default: path(mdiPizza) },
        coffee: { default: path(mdiCoffee) },
        beer: { default: path(mdiBeer) },
        wine: { default: path(mdiGlassWine) },
        apple: { default: path(mdiFoodApple) },
        cupcake: { default: path(mdiCupcake) },
        ice_cream: { default: path(mdiIceCream) },
        hamburger: { default: path(mdiHamburger) },
        noodles: { default: path(mdiNoodles) },
        rice: { default: path(mdiRice) },
        drumstick: { default: path(mdiFoodDrumstick) },
        candy_cane: { default: path(mdiCandycane) },
        cookie: { default: path(mdiCookie) },
        cake: { default: path(mdiCakeVariant) },
        grapes: { default: path(mdiFruitGrapes) },
        cherries: { default: path(mdiFruitCherries) },
        carrot: { default: path(mdiCarrot) },
        corn: { default: path(mdiCorn) },
        chili: { default: path(mdiChiliMild) },
        muffin: { default: path(mdiMuffin) },
        egg: { default: path(mdiEgg) },
        baguette: { default: path(mdiBaguette) },
        cheese: { default: path(mdiCheese) },
      },
    },
    people: {
      default: path(mdiAccount),
      deviceClasses: {
        person: { default: path(mdiAccount) },
        baby: { default: path(mdiBaby) },
        male: { default: path(mdiHumanMale) },
        female: { default: path(mdiHumanFemale) },
        child: { default: path(mdiHumanChild) },
        couple: { default: path(mdiHumanMaleFemale) },
        greeting: { default: path(mdiHumanGreeting) },
        wheelchair: { default: path(mdiHumanWheelchair) },
        run: { default: path(mdiRun) },
        walk: { default: path(mdiWalk) },
        dance: { default: path(mdiHumanFemaleDance) },
        yoga: { default: path(mdiYoga) },
        meditation: { default: path(mdiMeditation) },
        weight_lifter: { default: path(mdiWeightLifter) },
        swim: { default: path(mdiSwim) },
        hiking: { default: path(mdiHiking) },
        bike: { default: path(mdiBike) },
      },
    },
    common: {
      default: path(mdiBell),
      deviceClasses: {
        bell: { default: path(mdiBell) },
        clock: { default: path(mdiClock) },
        calendar: { default: path(mdiCalendar) },
        email: { default: path(mdiEmail) },
        phone: { default: path(mdiPhone) },
        wifi: { default: path(mdiWifi) },
        bluetooth: { default: path(mdiBluetooth) },
        music: { default: path(mdiMusic) },
        image: { default: path(mdiImage) },
        video: { default: path(mdiVideo) },
        book: { default: path(mdiBook) },
        trash: { default: path(mdiTrashCan) },
        recycle: { default: path(mdiRecycle) },
        earth: { default: path(mdiEarth) },
        map_marker: { default: path(mdiMapMarker) },
        flag: { default: path(mdiFlag) },
        key: { default: path(mdiKey) },
        gift: { default: path(mdiGift) },
        tag: { default: path(mdiTag) },
        basket: { default: path(mdiBasket) },
        cart: { default: path(mdiCart) },
        search: { default: path(mdiMagnify) },
        settings: { default: path(mdiCog) },
        info: { default: path(mdiInformation) },
        help: { default: path(mdiHelp) },
        check_circle: { default: path(mdiCheckCircle) },
        close_circle: { default: path(mdiCloseCircle) },
        plus_circle: { default: path(mdiPlusCircle) },
        minus_circle: { default: path(mdiMinusCircle) },
      },
    },
    science: {
      default: path(mdiAtom),
      deviceClasses: {
        atom: { default: path(mdiAtom) },
        dna: { default: path(mdiDna) },
        flask: { default: path(mdiFlask) },
        microscope: { default: path(mdiMicroscope) },
        telescope: { default: path(mdiTelescope) },
        rocket: { default: path(mdiRocket) },
        satellite: { default: path(mdiSatelliteVariant) },
        binoculars: { default: path(mdiBinoculars) },
        compass: { default: path(mdiCompass) },
        anchor: { default: path(mdiAnchor) },
        magnet: { default: path(mdiMagnet) },
      },
    },
    weather: {
      default: path(mdiWeatherSunny),
      deviceClasses: {
        sunny: { default: path(mdiWeatherSunny) },
        night: { default: path(mdiWeatherNight) },
        cloudy: { default: path(mdiWeatherCloudy) },
        rainy: { default: path(mdiWeatherRainy) },
        snowy: { default: path(mdiWeatherSnowy) },
        windy: { default: path(mdiWeatherWindy) },
        lightning: { default: path(mdiWeatherLightning) },
        fog: { default: path(mdiWeatherFog) },
        thermometer_high: { default: path(mdiThermometerHigh) },
        thermometer_low: { default: path(mdiThermometerLow) },
        island: { default: path(mdiIsland) },
        campfire: { default: path(mdiCampfire) },
        tent: { default: path(mdiTent) },
        candle: { default: path(mdiCandle) },
        snowflake: { default: path(mdiSnowflake) },
      },
    },
    fun: {
      default: path(mdiEmoticonHappy),
      deviceClasses: {
        emoticon: { default: path(mdiEmoticon) },
        happy: { default: path(mdiEmoticonHappy) },
        sad: { default: path(mdiEmoticonSad) },
        cool: { default: path(mdiEmoticonCool) },
        robot: { default: path(mdiRobot) },
        alien: { default: path(mdiAlien) },
        skull: { default: path(mdiSkull) },
        crown: { default: path(mdiCrown) },
        shield: { default: path(mdiShield) },
        sword: { default: path(mdiSword) },
        palette: { default: path(mdiPalette) },
        brush: { default: path(mdiBrush) },
        spray_bottle: { default: path(mdiSprayBottle) },
        pencil: { default: path(mdiPencil) },
        scissors: { default: path(mdiContentCut) },
      },
    },
    buildings: {
      default: path(mdiHome),
      deviceClasses: {
        home: { default: path(mdiHome) },
        home_outline: { default: path(mdiHomeOutline) },
        floor_1: { default: path(mdiHomeFloor1) },
        floor_2: { default: path(mdiHomeFloor2) },
        floor_3: { default: path(mdiHomeFloor3) },
        office: { default: path(mdiOfficeBuilding) },
        domain: { default: path(mdiDomain) },
        city: { default: path(mdiCity) },
        warehouse: { default: path(mdiWarehouse) },
        barn: { default: path(mdiBarn) },
      },
    },
    medical: {
      default: path(mdiPill),
      deviceClasses: {
        pill: { default: path(mdiPill) },
        hospital: { default: path(mdiHospitalBox) },
        medical_bag: { default: path(mdiMedicalBag) },
        stethoscope: { default: path(mdiStethoscope) },
        needle: { default: path(mdiNeedle) },
        virus: { default: path(mdiVirusOutline) },
      },
    },
    numbers: {
      default: path(mdiNumeric1),
      deviceClasses: {
        "0": { default: path(mdiNumeric0) },
        "1": { default: path(mdiNumeric1) },
        "2": { default: path(mdiNumeric2) },
        "3": { default: path(mdiNumeric3) },
        "4": { default: path(mdiNumeric4) },
        "5": { default: path(mdiNumeric5) },
        "6": { default: path(mdiNumeric6) },
        "7": { default: path(mdiNumeric7) },
        "8": { default: path(mdiNumeric8) },
        "9": { default: path(mdiNumeric9) },
        a: { default: path(mdiAlphaA) },
        b: { default: path(mdiAlphaB) },
        c: { default: path(mdiAlphaC) },
      },
    },
  },
};
