import {
  mdiCeilingLight,
  mdiLightbulbOff,
  mdiLightSwitch,
  mdiWindowShutter,
  mdiWindowShutterOpen,
  mdiChartBar,
  mdiHomeThermometer,
  mdiWaterPercent,
  mdiGauge,
  mdiFlash,
  mdiBatteryHigh,
  mdiWeatherSunny,
  mdiMoleculeCo2,
  mdiAlertCircle,
  mdiGasCylinder,
  mdiWater,
  mdiPowerPlug,
  mdiMotionSensor,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiWindowOpenVariant,
  mdiWindowClosedVariant,
  mdiVibrate,
  mdiSmokeDetectorVariant,
  mdiAccountGroup,
  mdiAccessPoint,
  mdiShieldCheck,
  mdiVolumeHigh,
  mdiFan,
  mdiCamera,
  mdiSpeaker,
  mdiPlay,
  mdiPause,
  mdiLock,
  mdiLockOpen,
  mdiFire,
  mdiSnowflake,
  mdiSync,
  mdiWaterOutline,
  mdiPower,
  mdiHexagonOutline,
  mdiLightningBolt,
  mdiFloorLamp,
  mdiWallSconce,
  mdiLedStrip,
  mdiHomeLightbulbOutline,
  mdiMovieOpen,
  mdiScriptText,
  mdiRobotHappy,
  mdiGestureTap,
  mdiSofa,
  mdiBed,
  mdiTable,
  mdiChairRolling,
  mdiDesk,
  mdiFlower,
  mdiToilet,
  mdiShower,
  mdiWaterPump,
  mdiBathtub,
  mdiFridge,
  mdiStove,
  mdiDishwasher,
  mdiTelevision,
  mdiWardrobe,
  mdiBookshelf,
} from "@mdi/js";
import type { IconPack, IconEntry, IconStateStyle } from "../types";

function path(
  d: string,
  opts?: { stateStyles?: Record<string, IconStateStyle>; defaultStyle?: IconStateStyle },
): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: opts?.defaultStyle ?? { opacity: 1, colorMode: "static" },
    stateStyles: opts?.stateStyles ?? {
      on: { opacity: 1, colorMode: "static" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
      unknown: { opacity: 0.3, colorMode: "static" },
    },
  };
}

function lightPath(d: string): IconEntry {
  return {
    icon: { type: "path", value: d },
    defaultStyle: { opacity: 1, colorMode: "entity_rgb" },
    stateStyles: {
      on: { opacity: 1, colorMode: "entity_rgb" },
      off: { opacity: 0.5, colorMode: "static" },
      unavailable: { opacity: 0.3, colorMode: "static" },
    },
  };
}

export const mdiHomePack: IconPack = {
  id: "mdi-home",
  name: "Home Style",
  description: "Home-focused icons — ceiling lights, floor lamps, wall sconces",
  fallback: path(mdiHexagonOutline),
  domains: {
    light: {
      default: lightPath(mdiCeilingLight),
      states: {
        off: lightPath(mdiLightbulbOff),
      },
      deviceClasses: {
        floor_lamp: { default: lightPath(mdiFloorLamp) },
        wall_light: { default: lightPath(mdiWallSconce) },
        led_strip: { default: lightPath(mdiLedStrip) },
      },
    },
    switch: { default: path(mdiLightSwitch) },
    cover: {
      default: path(mdiWindowShutter),
      states: {
        open: path(mdiWindowShutterOpen),
        opening: path(mdiWindowShutterOpen),
        closed: path(mdiWindowShutter),
        closing: path(mdiWindowShutter),
      },
    },
    sensor: {
      default: path(mdiChartBar),
      deviceClasses: {
        temperature: { default: path(mdiHomeThermometer) },
        humidity: { default: path(mdiWaterPercent) },
        pressure: { default: path(mdiGauge) },
        power: { default: path(mdiFlash) },
        energy: { default: path(mdiLightningBolt) },
        battery: { default: path(mdiBatteryHigh) },
        illuminance: { default: path(mdiWeatherSunny) },
        carbon_dioxide: { default: path(mdiMoleculeCo2) },
        carbon_monoxide: { default: path(mdiAlertCircle) },
        gas: { default: path(mdiGasCylinder) },
        moisture: { default: path(mdiWater) },
        plug: { default: path(mdiPowerPlug) },
      },
    },
    binary_sensor: {
      default: path(mdiHomeLightbulbOutline),
      deviceClasses: {
        motion: { default: path(mdiMotionSensor) },
        door: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        window: {
          default: path(mdiWindowClosedVariant),
          states: { on: path(mdiWindowOpenVariant), off: path(mdiWindowClosedVariant) },
        },
        vibration: { default: path(mdiVibrate) },
        smoke: { default: path(mdiSmokeDetectorVariant) },
        occupancy: { default: path(mdiAccountGroup) },
        opening: {
          default: path(mdiDoorClosed),
          states: { on: path(mdiDoorOpen), off: path(mdiDoorClosed) },
        },
        presence: { default: path(mdiAccessPoint) },
        problem: { default: path(mdiAlertCircle) },
        safety: { default: path(mdiShieldCheck) },
        sound: { default: path(mdiVolumeHigh) },
      },
    },
    climate: {
      default: path(mdiHomeThermometer),
      states: {
        heat: path(mdiFire),
        cool: path(mdiSnowflake),
        heat_cool: path(mdiSync),
        auto: path(mdiSync),
        dry: path(mdiWaterOutline),
        fan_only: path(mdiFan),
        off: path(mdiPower),
      },
    },
    fan: { default: path(mdiFan) },
    camera: { default: path(mdiCamera) },
    media_player: {
      default: path(mdiSpeaker),
      states: {
        playing: path(mdiPlay),
        paused: path(mdiPause),
      },
    },
    lock: {
      default: path(mdiLock),
      states: {
        locked: path(mdiLock),
        unlocked: path(mdiLockOpen),
      },
    },
    scene: { default: path(mdiMovieOpen) },
    script: { default: path(mdiScriptText) },
    automation: { default: path(mdiRobotHappy) },
    button: { default: path(mdiGestureTap) },
    furniture: {
      default: path(mdiChairRolling),
      deviceClasses: {
        sofa: { default: path(mdiSofa) },
        bed: { default: path(mdiBed) },
        table: { default: path(mdiTable) },
        chair: { default: path(mdiChairRolling) },
        desk: { default: path(mdiDesk) },
        plant: { default: path(mdiFlower) },
        door: { default: path(mdiDoorOpen) },
        window: { default: path(mdiWindowOpenVariant) },
        toilet: { default: path(mdiToilet) },
        shower: { default: path(mdiShower) },
        sink: { default: path(mdiWaterPump) },
        bathtub: { default: path(mdiBathtub) },
        fridge: { default: path(mdiFridge) },
        oven: { default: path(mdiStove) },
        dishwasher: { default: path(mdiDishwasher) },
        tv: { default: path(mdiTelevision) },
        wardrobe: { default: path(mdiWardrobe) },
        bookshelf: { default: path(mdiBookshelf) },
      },
    },
  },
};
