<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Components\Room.razor~RF2675b586.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="NLog" Version="5.1.2" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeLayout.Application\HomeLayout.Application.csproj" />
    <ProjectReference Include="..\HomeLayout.Common\HomeLayout.Common.csproj" />
    <ProjectReference Include="..\HomeLayout.Domain\HomeLayout.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\images\icons\*.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\images\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\lib\roundslider\roundslider.min.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\lib\roundslider\roundslider.min.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
